import { test, expect } from '@playwright/test';
import { accountFixture, trainingReadyData } from './account-fixture';
import { DEFAULT_EXERCISES } from '../../src/data/seed';
import { makeRir } from '../../src/domain/engine';
import { materializeCycles } from '../../src/domain/training';

test('mobile targets reconcile across days, show shortfalls and save without resetting account history', async ({page}) => {
  const data = trainingReadyData(); materializeCycles(data); data.settings.strict = false;
  const slot = (name:string,sets:number,id:string) => ({...data.plan.days[2]!.exercises[0]!,id,exerciseId:DEFAULT_EXERCISES.find(e=>e.name===name)!.id,sets,rir:makeRir(sets)});
  data.plan.days[2]!.exercises=[slot('Seated Hamstring Curls',2,'seated'),slot('Lying Hamstring Curls',3,'lying-a'),slot('Leg Extension',11,'quad-a'),slot('Standing Calf Raise (Machine)',5,'calf-a')];
  data.plan.days[5]!.exercises=[slot('Lying Hamstring Curls',1,'lying-b'),slot('Leg Extension',1,'quad-b'),slot('Standing Calf Raise (Machine)',5,'calf-b')];
  data.plan.targets={quads:12,hamstrings:12,gastrocnemius:10};
  data.cycles!.push({...data.cycles![0]!,id:'archived-cycle',name:'Preserved older cycle',startDate:'2026-08-01',endedAt:'2026-09-01',plan:structuredClone(data.plan)});
  const archived=structuredClone(data.cycles);const strength=structuredClone(data.strength);
  const account=await accountFixture(page,data);
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await page.getByRole('button',{name:'Start session',exact:true}).click();
  await page.getByLabel('Set 1 reps',{exact:true}).fill('8');
  await page.getByLabel('Set 1 reps',{exact:true}).blur();
  await expect.poll(()=>account.getHead().metadata.activeSession?.exercises[0].sets[0].reps).toBe(8);
  await expect(page.getByRole('button',{name:'Log set 1',exact:true})).toBeEnabled();
  await page.getByRole('button',{name:'Log set 1',exact:true}).click();
  await expect(page.getByRole('button',{name:'Unlog set 1',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Finish session',exact:true}).click();
  await page.getByRole('button',{name:/Finish with .* unlogged sets/}).click();
  await expect.poll(()=>account.getHead().records.length).toBe(1);
  const history=structuredClone(account.getHead().records);
  const logs=structuredClone([...account.records.values()]);
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();
  await page.getByRole('button',{name:'Your plan',exact:true}).click();
  await expect(page.getByLabel('Automatic set limit per exercise')).toHaveValue('6');
  await page.getByRole('button',{name:'Adjust exercise sets to targets'}).click();
  await page.getByRole('button',{name:'Day 3 Legs',exact:true}).click();
  await expect(page.locator('.plan-row').filter({hasText:'Leg Extension'})).toContainText('6 sets');
  await expect(page.locator('.plan-row').filter({hasText:'Seated Hamstring Curls'})).toContainText('3 sets');
  await page.getByRole('button',{name:'Day 6 Lower',exact:true}).click();
  await expect(page.locator('.plan-row').filter({hasText:'Leg Extension'})).toContainText('6 sets');
  await expect(page.locator('.plan-row').filter({hasText:'Lying Hamstring Curls'})).toContainText('6 sets');
  await page.getByLabel('Quads target').fill('20');
  await page.getByRole('button',{name:'Adjust exercise sets to targets'}).click();
  await expect(page.getByText(/Planned \/ target: Quads 12\/20/)).toBeVisible();
  await page.getByLabel('Automatic set limit per exercise').fill('4');
  await page.getByRole('button',{name:'Adjust exercise sets to targets'}).click();
  await expect(page.locator('.plan-row').filter({hasText:'Leg Extension'})).toContainText('4 sets');
  await page.getByLabel('Quads target').fill('8');await page.getByLabel('Hamstrings target').fill('8');
  await page.getByRole('button',{name:'Adjust exercise sets to targets'}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  // Adjusting the draft cannot save to the account until Save plan is chosen.
  expect(account.getHead().metadata.plan.days[2].exercises[2].sets).toBe(11);
  await page.getByRole('button',{name:'Save plan',exact:false}).click();
  await expect.poll(()=>account.getHead().metadata.plan.days[2].exercises[2].sets).toBe(4);
  expect(account.getHead().metadata.cycles).toEqual(archived);
  expect(account.getHead().metadata.strength).toEqual(strength);
  expect(account.getHead().records).toEqual(history);
  expect([...account.records.values()]).toEqual(logs);
  await page.reload();await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Your plan',exact:true}).click();
  await expect(page.getByLabel('Quads target')).toHaveValue('8');
});
