"""Regenerate source-derived seed data without network access or guessed FSA weights."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT / 'source/live-sheet.json').read_text())
sheet = next(s for s in source['sheets'] if s['properties']['title'] == 'Guide Sheet')
rows = sheet['data'][0]['rowData']

def cell(row, col):
    values = rows[row - 1].get('values', [])
    return values[col] if col < len(values) else {}

def value(row, col):
    return cell(row, col).get('formattedValue', '').strip()

muscle_ids = ['chest', 'anterior-delts', 'lateral-delts', 'rear-delts', 'triceps', 'biceps', 'brachialis', 'brachioradialis', 'lats', 'mid-low-traps-rhomboids', 'upper-traps', 'quads', 'hamstrings', 'glute-max', 'glute-med-min', 'adductors', 'gastrocnemius', 'soleus', 'erector-spinae']
muscles = [{'id': ident, 'name': value(row, 8)} for row, ident in zip(range(5, 24), muscle_ids)]
contributions = {}
expected = {}
for row, muscle in zip(range(5, 24), muscles):
    expected[muscle['id']] = {'direct': float(value(row, 9)), 'fractional': float(value(row, 10)), 'total': float(value(row, 11))}
    for col in (9, 10):
        formula = cell(row, col)['userEnteredValue']['formulaValue'].removeprefix('=')
        if formula == '0':
            continue
        for term in formula.split('+'):
            matched = re.fullmatch(r'SUM\((D\d+(?:,D\d+)*)\)(?:\*(0\.\d+|1))?', term)
            if not matched:
                raise ValueError(f'Unsupported formula J/K row {row}: {formula}')
            coefficient = float(matched.group(2) or 1)
            for ref in matched.group(1).split(','):
                contributions.setdefault(int(ref[1:]), []).append({'muscle': muscle['id'], 'coefficient': coefficient})

exercise_rows = [i for i in range(1, len(rows) + 1) if re.fullmatch(r'\d+', value(i, 3))]
unique = {}
exercises = []
days = []
for start, end, ident, name, kind in [(5,11,'push','Push + NCP','training'),(13,18,'pull','Pull + NCP','training'),(20,26,'legs','Legs','training'),(28,28,'rest-1','Active Rest','rest'),(30,37,'upper','Upper','training'),(39,45,'lower','Lower','training'),(47,47,'rest-2','Active Rest','rest')]:
    day = {'id':ident,'name':name,'kind':kind,'exercises':[]}
    for row in range(start, end + 1):
        if row not in exercise_rows:
            continue
        name = value(row, 2)
        rir = [p.strip().replace('⚠️','') for p in value(row, 5).split(',')]
        rir = [int(p) if p.isdigit() else p for p in rir]
        if name not in unique:
            exercise_id = 'source-' + str(row)
            unique[name] = exercise_id
            equipment = 'Bodyweight' if 'Pushups' in name or 'Chinups' in name else 'Cable' if any(t in name for t in ['Cable', 'Pulldown', 'Pullovers']) else 'Machine' if any(t in name for t in ['Machine', 'Leg Press', 'Hack Squat', 'Leg Extension', 'Hamstring Curls']) else 'Dumbbell' if any(t in name for t in ['Dumbbell', 'Hammer', 'Lateral', 'Incline Curls']) else 'Barbell' if any(t in name for t in ['Bench', 'RDL', 'Ez-Bar']) else 'Other'
            exercises.append({'id':exercise_id,'name':name,'equipment':equipment,'contributions':contributions.get(row,[]),'source':f"{source['spreadsheetUrl']}#gid=0&range=C{row}:F{row}",'beyondFailureAllowed':'<0' in rir})
        else:
            existing = next(e for e in exercises if e['id'] == unique[name])
            if existing['contributions'] != contributions.get(row,[]):
                raise ValueError(f'Repeated exercise has differing coefficients: {name}')
            existing['beyondFailureAllowed'] |= '<0' in rir
        rep_min,rep_max = [int(p.strip()) for p in value(row,4).split('-')]
        bodyweight = 'Pushups' in name or 'Chinups' in name
        day['exercises'].append({'id':f'slot-{row}','exerciseId':unique[name],'sets':int(value(row,3)),'repMin':rep_min,'repMax':rep_max,'rir':rir,'load':0,'increment':0.5,'loadMode':'bodyweight' if bodyweight else 'external'})
    days.append(day)

target_ids = ['chest','lats','biceps','triceps','quads','hamstrings','glute-max','gastrocnemius','lateral-delts']
plan = {'id':'pandr5-source-v1.1.1','name':'PANDR-5 · Source template','days':days,'targets':{m:max(10,min(20,expected[m]['total'])) for m in target_ids},'updatedAt':'2026-09-15T00:00:00.000Z'}
header = '// Generated by scripts/extract-source.py from the supplied live sheet.\n// Exercise equipment labels are UI descriptors; every coefficient comes from J/K formulas.\nimport type { AppData, Exercise, TrainingPlan } from \'../domain/types\';\n\n'
output = header + 'export const SOURCE_URL = '+json.dumps(source['spreadsheetUrl'])+';\n\n'
for name,typ,data in [('MUSCLES',None,muscles),('SOURCE_TOTALS',None,expected),('DEFAULT_EXERCISES','Exercise[]',exercises),('DEFAULT_PLAN','TrainingPlan',plan)]:
    output += f'export const {name}'+(f': {typ}' if typ else '')+' = '+json.dumps(data,indent=2,ensure_ascii=False)+';\n\n'
output += '''export function createInitialData(): AppData {
  const now = new Date();
  const startDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  return {
    schemaVersion: 1,
    id: crypto.randomUUID(),
    updatedAt: now.toISOString(),
    settings: { name: '', strict: true, unit: 'kg', startDate, increasePercent: 2.5, decreasePercent: 2.5, restSeconds: 120 },
    plan: structuredClone(DEFAULT_PLAN),
    exercises: structuredClone(DEFAULT_EXERCISES),
    sessions: [],
    checkIns: [],
  };
}
'''
(ROOT/'src/data/seed.ts').write_text(output)
print(f'Extracted {len(exercises)} source exercises, {len(days)} days, {len(muscles)} muscles.')
