import { useEffect, useState, Component, type ReactNode, type ErrorInfo } from 'react';
import { Activity, ArrowUpRight, BookOpen, CalendarDays, ChartNoAxesColumnIncreasing, CheckCircle2, Cloud, Download, Dumbbell, LoaderCircle, Menu, Settings2, X, WifiOff } from 'lucide-react';
import { useStore } from './useStore';
import { Train } from './Train';
import { Plan } from './Plan';
import { History } from './History';
import { Library } from './Library';
import { Settings } from './Settings';
import { Method } from './Method';
import { Button, Notice } from './components';
import { registerSW } from 'virtual:pwa-register';
const navigation=[['train','Train',Dumbbell],['plan','Your plan',CalendarDays],['history','History',ChartNoAxesColumnIncreasing],['library','Exercise library',BookOpen],['method','The method',Activity],['settings','Settings',Settings2]] as const;
type Page=typeof navigation[number][0];
interface InstallPrompt extends Event { prompt:()=>Promise<void>; userChoice:Promise<{outcome:string}> }
function Application(){
 const store=useStore();const {data,update,error,setError,status,busy,ready,pending,interrupted,profile,email,client,sync,signOut}=store;
 const [anchor,setAnchor]=useState<{id:string;key:number}>();
 const [page,setPage]=useState<Page>([location.search, location.hash.slice(1)].some(value => /(?:[?#&]|^)(?:code|error|error_description)=/.test(value)) ? 'settings' : 'train');const [mobileOpen,setMobileOpen]=useState(false);const [online,setOnline]=useState(navigator.onLine);const [install,setInstall]=useState<InstallPrompt>();const [updater,setUpdater]=useState<(()=>Promise<void>)>();
 useEffect(()=>{const network=()=>setOnline(navigator.onLine);const prompt=(event:Event)=>{event.preventDefault();setInstall(event as InstallPrompt)};const handleError=(event:PromiseRejectionEvent)=>{setError(event.reason?.message||String(event.reason));event.preventDefault()};window.addEventListener('online',network);window.addEventListener('offline',network);window.addEventListener('beforeinstallprompt',prompt);window.addEventListener('unhandledrejection',handleError);return ()=>{window.removeEventListener('online',network);window.removeEventListener('offline',network);window.removeEventListener('beforeinstallprompt',prompt);window.removeEventListener('unhandledrejection',handleError)}},[setError]);
 useEffect(()=>{if(!['http:','https:'].includes(location.protocol))return;const updateSW=registerSW({onNeedRefresh(){setUpdater(()=>()=>updateSW(true))},onRegisterError(e){console.warn('Offline installation unavailable',e)}})},[]);
 function go(next:Page,section?:string){setPage(next);setAnchor(section?{id:section,key:Date.now()}:undefined);setMobileOpen(false);window.scrollTo({top:0,behavior:'instant'})}
 useEffect(()=>{if(anchor&&ready)requestAnimationFrame(()=>{const el=document.getElementById(anchor.id);el?.scrollIntoView({block:'start',behavior:'instant'});el?.focus({preventScroll:true})})},[anchor,page,ready]);
 useEffect(()=>{const system=matchMedia('(prefers-color-scheme: dark)');const apply=()=>{document.documentElement.dataset.theme=data?.settings.theme==='dark'||((data?.settings.theme??'automatic')==='automatic'&&system.matches)?'dark':'light'};apply();system.addEventListener('change',apply);return ()=>system.removeEventListener('change',apply)},[data?.settings.theme]);
 useEffect(()=>{setMobileOpen(false)},[data?.activeSession?.id]);
 const focused=page==='train'&&!!data?.activeSession;
 if(!ready||!data)return <main className="loading-screen"><div className="brand">PANDR<span>—5</span></div>{error?<><Notice tone="error">{error}</Notice>{profile!=='local'&&<Button onClick={()=>void store.openProfile(profile,email)}>Retry opening account</Button>}<Button onClick={()=>void store.openProfile('local')}>Open unsaved preview</Button></>:<><LoaderCircle className="spinning"/><p>Opening your training log…</p></>}</main>;
 return <div className={`app-shell ${focused?'workout-focus':''}`}><div className="mobile-top"><button className="icon-button" aria-label="Open navigation" onClick={()=>setMobileOpen(true)}><Menu/></button><strong>PANDR—5</strong><span className="save-dot"/></div>{mobileOpen&&<button className="nav-shade" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}
 <aside className={`sidebar ${mobileOpen?'open':''}`} inert={focused&&!mobileOpen}><div className="brand">PANDR<span>—5</span></div><button className="mobile-close icon-button" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}><X/></button><nav>{navigation.map(([id,label,Icon])=><button key={id} className={page===id?'selected':''} aria-current={page===id?'page':undefined} onClick={()=>go(id)}><Icon size={21} strokeWidth={1.7}/><span>{label}</span>{id==='train'&&data.activeSession&&<span className="session-dot"/>}</button>)}</nav><div className="sidebar-bottom">{install&&<Button onClick={async()=>{await install.prompt();const choice=await install.userChoice;if(choice.outcome==='accepted')setInstall(undefined)}}><Download size={17}/> Install app</Button>}<div className="save-status">{!online?<WifiOff size={19}/>:profile==='local'?<CheckCircle2 size={19}/>:<Cloud size={19}/>}<span>{!online?'Offline · cloud saving unavailable':status}<small>{data.settings.name||'Your training space'}</small></span></div><button className="text-link" onClick={()=>go('settings','account')}>{profile==='local'?'Sign in with Google':email} <ArrowUpRight size={13}/></button></div></aside>
 <main className="main-content" aria-busy={busy}>{focused&&<button className="button workout-navigation" aria-label="Open navigation" onClick={()=>setMobileOpen(true)}><Menu size={18}/> Menu</button>}{interrupted&&<Notice tone="error">An account save was interrupted by a sign-in change. Keep this tab open and sign back in with that Google account to recover and save it.</Notice>}{profile==='local'&&<Notice><strong>Unsaved preview.</strong> Sign in with Google to save your training and access it on other devices. Preview changes disappear when you close or reload this page. <button className="text-button" onClick={()=>go('settings','account')}>Sign in</button></Notice>}{pending&&status.startsWith('Not saved')&&<Notice tone="error">Changes have not reached your account yet. Keep this tab open. <button className="text-button" onClick={()=>void sync()}>Retry saving</button></Notice>}{error&&<div className="global-error"><Notice tone="error">{error} <button className="text-button" onClick={()=>setError('')}>Dismiss</button></Notice></div>}{updater&&!data.activeSession&&<Notice>A new version is ready. Your saved data will be kept. <Button small onClick={()=>void updater()}>Update app</Button></Notice>}<fieldset className="app-fieldset" disabled={busy}>
 {page==='train'&&<Train key={`${profile}-${data.activeCycleId??'first'}`} data={data} update={update} goPlan={()=>go('plan')}/>}
 {page==='plan'&&<Plan key={`${profile}-${data.settings.strict}`} data={data} update={update}/>}
 {page==='history'&&<History data={data}/>}
 {page==='library'&&<Library data={data} update={update}/>}
 {page==='method'&&<Method/>}
 {page==='settings'&&<Settings key={profile} data={data} update={update} client={client} profile={profile} email={email} sync={sync} signOut={signOut} pending={pending} goMethod={section=>go('method',section)} goHistory={()=>go('history')} goPlan={()=>go('plan')}/>}
 </fieldset></main>{(busy||pending)&&<div className="busy-indicator" role="status"><LoaderCircle size={17} className="spinning"/> Saving to your account…</div>}</div>
}
class AppBoundary extends Component<{children:ReactNode},{error:string}> {state={error:''};static getDerivedStateFromError(error:Error){return {error:error.message}}componentDidCatch(error:Error,info:ErrorInfo){console.error(error,info)}render(){return this.state.error?<main className="loading-screen"><h1>PANDR-5 couldn’t open.</h1><Notice tone="error">{this.state.error}</Notice><p>Your saved data has not been deleted.</p><Button onClick={()=>location.reload()}>Try again</Button></main>:this.props.children}}
export default function App(){return <AppBoundary><Application/></AppBoundary>}
