import { useState } from 'react';
import type { PlanExercise, Settings } from './domain/types';
import { Field, Notice } from './components';
import { barbellEquipment, defaultLoadIncrement, dumbbellEquipment } from './domain/equipment';

const loads = (text: string) => text.trim() ? text.split(',').filter(v => v.trim() !== '').map(v => Number(v.trim())) : [];
export function EquipmentSetup({ slot, unit, onChange }: { slot: PlanExercise; unit: Settings['unit']; onChange: (slot: PlanExercise) => void }) {
 const [available, setAvailable] = useState(slot.availableLoads?.join(', ') ?? '');
 const [added, setAdded] = useState(slot.bodyweight?.addedLoads.join(', ') ?? '');
 const [assistance, setAssistance] = useState(slot.bodyweight?.assistanceLoads.join(', ') ?? '');
 const [preset,setPreset] = useState('keep');
 const [expanded,setExpanded] = useState(!!slot.bodyweight || !!slot.availableLoads);
 return <details className="equipment-setup" open={expanded} onToggle={e=>setExpanded(e.currentTarget.open)}><summary>Equipment and bodyweight progression</summary>
 <p>Record the loads you actually have. The app keeps the 2–5% increase and 2–3% reduction limits; it cannot bridge a larger equipment gap automatically.</p>
 {!slot.bodyweight&&<><Field label="Equipment preset"><select value={preset} onChange={e=>{const value=e.target.value;setPreset(value);if(value==='keep')return;const setup=value==='dumbbell-rack'?dumbbellEquipment(unit):value==='five-pound'?{increment:defaultLoadIncrement(unit),availableLoads:undefined}:barbellEquipment(unit,value==='barbell-2.5'?2.5:value==='barbell-1'?1:5);setAvailable(setup.availableLoads?.join(', ')??'');onChange({...slot,...setup})}}><option value="keep">Keep current equipment</option><option value="barbell-standard">45 lb bar · 5, 10, 25, 45 lb plates</option><option value="dumbbell-rack">Dumbbells · 2.5 lb steps through 50 lb, then 5 lb</option><option value="five-pound">5 lb load steps · machines, cables or racks</option><option value="barbell-2.5">45 lb bar · includes 2.5 lb plates</option><option value="barbell-1">45 lb bar · includes 1 lb plates</option></select></Field><p className="muted">Barbell presets use total load on a 45 lb bar; equal 5 lb plates add 10 lb. The dumbbell rack preset records one dumbbell, with 2.5 lb steps from 5–50 lb and 5 lb steps above 50 through 200 lb. Edit the exact list to match your rack. Machines and cables default to 5 lb steps; use the actual stack increments or confirmed available loads for your setup.</p></>}
 <label className="check-row"><span>Set up bodyweight resistance</span><input type="checkbox" checked={!!slot.bodyweight} onChange={e => onChange({ ...slot, availableLoads: undefined, bodyweight: e.target.checked ? { resistance: 0, addedLoads: loads(added), assistanceLoads: loads(assistance) } : undefined })}/></label>
 {slot.bodyweight ? <><Notice>Enter the resistance moved in this exact setup. Full body mass can be used when lifting the whole body, such as a pull-up. For partially supported movements, use a measured supported load. There is no universal bodyweight percentage. Band labels alone do not measure assistance; use calibrated assistance for the same setup and range of motion. Update this value when your body mass or setup changes.</Notice>
 <Field label={`Bodyweight resistance (${unit})`} hint="Before adding weight or subtracting assistance. This is a mechanical estimate, not a measure of muscle force."><input aria-label={`Bodyweight resistance (${unit})`} type="number" min="0.01" step="any" value={slot.bodyweight.resistance || ''} onChange={e => onChange({ ...slot, bodyweight: { ...slot.bodyweight!, resistance: Number(e.target.value) } })}/></Field>
 <Field label={`Available added loads (${unit})`} hint="Positive total added loads, separated by commas. Leave blank if none."><input aria-label={`Available added loads (${unit})`} placeholder={unit==='lb'?'5, 10, 25, 45':'2.27, 4.54, 11.34, 20.41'} value={added} onChange={e => { setAdded(e.target.value); onChange({ ...slot, bodyweight: { ...slot.bodyweight!, addedLoads: loads(e.target.value) } }); }}/></Field>
 <Field label={`Available measured assistance (${unit})`} hint="Positive assistance amounts below the bodyweight resistance, separated by commas. Leave blank if none."><input aria-label={`Available measured assistance (${unit})`} placeholder="2, 4, 6" value={assistance} onChange={e => { setAssistance(e.target.value); onChange({ ...slot, bodyweight: { ...slot.bodyweight!, assistanceLoads: loads(e.target.value) } }); }}/></Field>
 <p>The next workout can move between assisted, unassisted, and added-weight modes when a confirmed option fits. External weight means added load with this setup enabled.</p></> : <><label className="check-row"><span>Use an exact list of available loads</span><input type="checkbox" checked={!!slot.availableLoads} onChange={e => onChange({ ...slot, availableLoads: e.target.checked ? loads(available) : undefined })}/></label>
 {slot.availableLoads && <Field label={`Available working loads (${unit})`} hint="Comma-separated total working loads. This list replaces the uniform increment; include microloads only if you have them."><input aria-label={`Available working loads (${unit})`} placeholder={unit==='lb'?'45, 55, 65, 75': '20, 25, 30, 35'} value={available} onChange={e => { setPreset('keep');setAvailable(e.target.value); onChange({ ...slot, availableLoads: loads(e.target.value) }); }}/></Field>}</>}
 </details>;
}
