import { useMemo, useState } from 'react';
import { ChevronRight, Download, TrendingUp } from 'lucide-react';
import type { AppData, Session } from './domain/types';
import { exportCsv } from './services/backup';
import { Button, download, Empty, Field, Modal } from './components';
export function History({data}:{data:AppData}) {
 const [selected,setSelected]=useState<Session>();const [filter,setFilter]=useState('');const [exerciseId,setExerciseId]=useState('');
 const history=[...data.sessions].sort((a,b)=>b.startedAt.localeCompare(a.startedAt));const visible=history.filter(s=>!filter||`${s.dayName} ${s.date} ${s.exercises.map(e=>e.name).join(' ')}`.toLowerCase().includes(filter.toLowerCase()));
 const loggedExercises=useMemo(()=>Array.from(new Map(data.sessions.flatMap(s=>s.exercises).map(e=>[e.exerciseId,e.name])).entries()),[data.sessions]);const records=[...history].reverse().flatMap(s=>s.exercises.filter(e=>e.exerciseId===(exerciseId||loggedExercises[0]?.[0])&&e.sets.some(x=>x.completed)).map(e=>({load:e.load,unit:e.unit,mode:e.loadMode,date:s.date,anchor:e.sets[e.recommendation?.anchorIndex??e.sets.length-1]})));
 return <><header className="page-heading"><div><h1>Your training, over time</h1><p>Every session. Every set. Always yours to keep.</p></div><Button onClick={()=>download('pandr-5-all-time.csv',exportCsv(data),'text/csv;charset=utf-8')}><Download size={17}/> Export all-time CSV</Button></header>{!history.length?<section className="panel"><Empty title="Your first session starts the story.">Complete a workout to see your training history and load trends here. Your all-time export also includes your plan and check-ins.</Empty></section>:<><section className="panel"><div className="section-head"><div><h2><TrendingUp size={22}/> Load history</h2><p>Recorded working loads, with the units used at the time.</p></div><select aria-label="Exercise for load history" value={exerciseId||loggedExercises[0]?.[0]} onChange={e=>setExerciseId(e.target.value)}>{loggedExercises.map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></div><div className="trend-chart">{records.slice(-16).map((r,i)=>{const same=records.filter(e=>e.unit===r.unit&&e.mode===r.mode);const max=Math.max(...same.map(e=>e.load),1);return <div className="trend-column" key={`${r.date}-${i}`}><span>{r.load} {r.unit}</span><div style={{height:`${Math.max(3,r.load/max*130)}px`}}/><small>{r.date.slice(5)}</small></div>})}</div><p className="muted">Bars are scaled separately for each unit and load type. Assistance loads decrease as strength improves.</p></section><div className="section-head history-toolbar"><h2>{history.length} saved session{history.length===1?'':'s'}</h2><input aria-label="Search history" placeholder="Search sessions or exercises…" value={filter} onChange={e=>setFilter(e.target.value)}/></div><section className="panel history-list">{visible.map(s=><button className="history-row" key={s.id} onClick={()=>setSelected(s)}><div className="history-date"><strong>{new Date(s.date+'T12:00:00').getDate()}</strong><small>{new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short'})}</small></div><div><h3>{s.dayName}</h3><p>Week {s.week}{s.pivot?' · Pivot':''} · {s.exercises.flatMap(e=>e.sets).filter(s=>s.completed).length} working sets · {s.date}</p></div><ChevronRight size={18}/></button>)}{!visible.length&&<p>No sessions match this search.</p>}</section></>}
 {data.checkIns.length>0&&<section className="panel"><h2>Recovery check-ins</h2>{[...data.checkIns].reverse().map(c=><div className="data-line" key={c.id}><span>{c.date} · Week {c.week}</span><span>{[['poorSleep','Poor sleep'],['runDown','Run-down'],['elevatedHr','Resting HR'],['lingeringSoreness','Soreness'],['performanceDip','Performance dip'],['jointPain','Joints']].filter(([k])=>c[k as keyof typeof c]===true).map(([,label])=>label).join(', ')||'No flags'}{c.notes&&` · ${c.notes}`}</span></div>)}</section>}
 {selected&&<Modal title={selected.dayName} onClose={()=>setSelected(undefined)}><p>{selected.date} · Week {selected.week}{selected.pivot?' · Pivot week':''}</p>{selected.exercises.map(e=><section className="history-exercise" key={e.slotId}><h3>{e.name}</h3><p>{e.load} {e.unit} · {e.loadMode} · target {e.repMin}–{e.repMax} reps</p><div className="history-sets">{e.sets.map(s=><div key={s.index}><small>SET {s.index+1}</small><strong>{s.completed?`${s.reps} reps`:'Unlogged'}</strong><span>{s.completed?`${s.rir<0?'<0':s.rir} RIR`:'—'}</span></div>)}</div>{e.recommendation&&<p>{e.recommendation.reason} Next: {e.recommendation.nextLoad} {e.unit}.</p>}{e.notes&&<p>{e.notes}</p>}</section>)}{selected.notes&&<Field label="Session notes"><p>{selected.notes}</p></Field>}</Modal>}
 </>
}
