import { useState } from 'react';
import { ArrowDown, ArrowUp, Check, Plus, SlidersHorizontal, Trash2 } from 'lucide-react';
import type { AppData, PlanExercise, Rir, TrainingPlan } from './domain/types';
import { calculateVolume, validatePlan, allocateSets, makeRir } from './domain/engine';
import { MUSCLES } from './data/seed';
import { availableExercises, catalogForPlan, matchesExercise, exerciseOrigin } from './data/catalog';
import { Button, Field, Modal, Notice, numberValue } from './components';
import type { Update } from './Train';
export function Plan({data,update}:{data:AppData;update:Update}) {
 const [draft,setDraft]=useState<TrainingPlan>(()=>structuredClone(data.plan));const [dayIndex,setDayIndex]=useState(0);const [slotId,setSlotId]=useState<string>();const [message,setMessage]=useState('');const [saved,setSaved]=useState(false);const [saving,setSaving]=useState(false);
 const exercises=availableExercises(data.exercises);
 const volumes=calculateVolume(draft,exercises);const issues=validatePlan(draft,exercises,data.settings.strict);const day=draft.days[dayIndex];
 function change(fn:(p:TrainingPlan)=>void){const p=structuredClone(draft);fn(p);setDraft(p);setSaved(false);setMessage('')}
 function allocate(){const result=allocateSets(draft,exercises,data.settings.strict);setDraft(result.plan);setSaved(false);setMessage(result.issues.filter(i=>i.severity==='error').map(i=>i.message).join(' ')||'Sets adjusted toward your targets. Review the plan and save when ready.')}
 async function save(){setSaving(true);try{await update(d=>({...d,exercises:catalogForPlan(d.exercises,draft),plan:{...draft,updatedAt:new Date().toISOString()}}));setSaved(true)}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <><header className="page-heading"><div><h1>Your plan</h1><p>{data.settings.strict?'The PANDR-5 framework, fitted to your training.':'Custom mode · your schedule, guided by PANDR-5 progression.'}</p></div><Button primary disabled={saving||issues.some(i=>i.severity==='error')||!!data.activeSession} onClick={()=>void save()}>{saved?'Saved':saving?'Saving…':'Save plan'} <Check size={17}/></Button></header>{data.activeSession&&<Notice>Finish your active session before changing the plan.</Notice>}{message&&<Notice>{message}</Notice>}{saved&&<Notice tone="success">Your plan is saved. It will be used for your next session.</Notice>}
 <section className="panel target-panel"><div className="section-head"><div><h2>Weekly muscle targets</h2><p>Full credit for primary muscles, fractional credit for supporting muscles.</p></div><Button onClick={allocate}><SlidersHorizontal size={17}/> Fit sets to targets</Button></div><div className="target-grid">{MUSCLES.map(m=>{const v=volumes.find(v=>v.muscle===m.id);const target=draft.targets[m.id];return <div className="target-control" key={m.id}><label><input type="checkbox" checked={target!==undefined} onChange={e=>change(p=>{if(e.target.checked)p.targets[m.id]=Math.min(20,Math.max(10,v?.total||10));else delete p.targets[m.id]})}/><strong>{m.name}</strong></label><div><span className={target!==undefined&&((v?.total||0)<10||(v?.total||0)>20)&&data.settings.strict?'warning-text':''}>{v?.total||0} <small>planned</small></span>{target!==undefined&&<input aria-label={`${m.name} target`} type="number" min={data.settings.strict?10:0} max={data.settings.strict?20:300} step="0.25" value={target} onChange={e=>change(p=>{p.targets[m.id]=numberValue(e.target.value)})}/>}</div><div className="bar"><i style={{width:`${Math.min(100,(v?.total||0)/(target||20)*100)}%`}}/></div></div>})}</div><p className="muted">Select the muscles you want to target. In constrained mode, every selected target and its planned effective volume must fall within 10–20 sets, spread over at least two days. Smaller supporting muscles remain visible. Exact targets depend on the exercises you choose.</p></section>
 <div className="week-strip">{draft.days.map((d,i)=><button key={d.id} className={dayIndex===i?'selected':''} onClick={()=>setDayIndex(i)}><span>Day {i+1}</span><strong>{d.name}</strong><i/></button>)}</div>
 <section className="panel"><div className="section-head"><div><h2>{day.name}</h2><p>{day.kind==='training'?`${day.exercises.length} exercises`:'Recovery day'}</p></div>{day.kind==='training'&&<Button onClick={()=>change(p=>{const e=exercises[0];p.days[dayIndex].exercises.push({id:crypto.randomUUID(),exerciseId:e.id,sets:3,repMin:8,repMax:12,rir:makeRir(3),load:0,increment:0.5,loadMode:'external'})})}><Plus size={17}/> Add exercise</Button>}</div>
 {!data.settings.strict&&<div className="form-grid"><Field label="Day name"><input value={day.name} onChange={e=>change(p=>{p.days[dayIndex].name=e.target.value})}/></Field><Field label="Day type"><select value={day.kind} onChange={e=>{if(e.target.value==='rest'&&day.exercises.length){setMessage('Remove the exercises from this day before changing it to recovery.');return}change(p=>{p.days[dayIndex].kind=e.target.value as 'rest'|'training'})}}><option value="training">Training</option><option value="rest">Recovery</option></select></Field></div>}
 {day.exercises.map((s,i)=><div className="plan-row" key={s.id}><span className="row-index">{String(i+1).padStart(2,'0')}</span><button className="text-button exercise-name" onClick={()=>setSlotId(s.id)}>{exercises.find(e=>e.id===s.exerciseId)?.name}</button><span>{s.sets} sets · {s.repMin}–{s.repMax} reps</span><div className="row-actions"><button className="icon-button" aria-label={`Move exercise ${i+1} up`} disabled={!i} onClick={()=>change(p=>{const a=p.days[dayIndex].exercises;[a[i-1],a[i]]=[a[i],a[i-1]]})}><ArrowUp size={16}/></button><button className="icon-button" aria-label={`Move exercise ${i+1} down`} disabled={i===day.exercises.length-1} onClick={()=>change(p=>{const a=p.days[dayIndex].exercises;[a[i+1],a[i]]=[a[i],a[i+1]]})}><ArrowDown size={16}/></button><button className="icon-button" aria-label={`Remove exercise ${i+1}`} onClick={()=>change(p=>{p.days[dayIndex].exercises.splice(i,1)})}><Trash2 size={16}/></button></div></div>)}
 {day.kind==='rest'&&<p className="muted">A scheduled recovery day. Your weekly check-in chooses active or passive recovery.</p>}</section>
 {issues.length>0&&<section className="panel validation-panel"><h3>Plan checks</h3>{issues.map((i,n)=><p className={i.severity==='error'?'warning-text':'muted'} key={n}>{i.message}</p>)}</section>}
 {slotId&&<EditSlot slot={day.exercises.find(s=>s.id===slotId)!} data={data} onClose={()=>setSlotId(undefined)} onSave={slot=>{change(p=>{const a=p.days[dayIndex].exercises;a[a.findIndex(s=>s.id===slot.id)]=slot});setSlotId(undefined)}}/>}
 </>
}
function EditSlot({slot,data,onSave,onClose}:{slot:PlanExercise;data:AppData;onSave:(slot:PlanExercise)=>void;onClose:()=>void}) {
 const exercises=availableExercises(data.exercises);
 const [s,setS]=useState(structuredClone(slot));const [error,setError]=useState('');const [query,setQuery]=useState('');const e=exercises.find(e=>e.id===s.exerciseId)!;
 return <Modal title="Edit exercise prescription" onClose={onClose}><Field label="Find an exercise"><input placeholder="Search the available library…" value={query} onChange={e=>setQuery(e.target.value)}/></Field><Field label="Exercise"><select aria-label="Exercise" value={s.exerciseId} onChange={e=>setS({...s,exerciseId:e.target.value,load:0,rir:makeRir(s.sets),loadMode:'external'})}>{exercises.filter(e=>e.id===s.exerciseId||matchesExercise(e,query)).map(e=><option key={e.id} value={e.id}>{e.name} · {exerciseOrigin(e)}</option>)}</select></Field><div className="form-grid"><Field label="Working sets"><input type="number" min="1" max="30" value={s.sets} onChange={e=>{const n=Math.min(30,Math.max(1,Math.round(numberValue(e.target.value,1))));setS({...s,sets:n,rir:makeRir(n,s.rir.at(-1)==='<0')})}}/></Field><Field label="Working load"><input type="number" min="0" step="0.25" value={s.load} onChange={e=>setS({...s,load:numberValue(e.target.value)})}/></Field><Field label="Minimum reps"><input type="number" min="1" value={s.repMin} onChange={e=>setS({...s,repMin:numberValue(e.target.value)})}/></Field><Field label="Maximum reps"><input type="number" min="1" value={s.repMax} onChange={e=>setS({...s,repMax:numberValue(e.target.value)})}/></Field><Field label="Smallest load increment" hint={`Available equipment increment in ${data.settings.unit}.`}><input type="number" min="0.01" step="0.25" value={s.increment} onChange={e=>setS({...s,increment:numberValue(e.target.value)})}/></Field><Field label="Load type"><select value={s.loadMode} onChange={e=>setS({...s,loadMode:e.target.value as PlanExercise['loadMode']})}><option value="external">External weight</option><option value="assistance">Assistance weight</option><option value="bodyweight">Bodyweight only</option></select></Field></div><h3>RIR staircase</h3><p className="muted">Repetitions in reserve: the clean reps you could still perform. &lt;0 is a beyond-failure finisher.</p><div className="rir-editor">{s.rir.map((r,i)=><Field label={`Set ${i+1}`} key={i}><select value={r} onChange={event=>{const value=event.target.value;setS({...s,rir:s.rir.map((v,j)=>i===j?(value==='0-1'||value==='<0'?value:Number(value)) as Rir:v)})}}>{[3,2,1,'0-1',0,...(e.beyondFailureAllowed&&i===s.sets-1&&i>0?['<0']:[])].map(v=><option key={v} value={v}>{v}</option>)}</select></Field>)}</div>{error&&<Notice tone="error">{error}</Notice>}<Button primary onClick={()=>{if(s.repMin<1||s.repMax<s.repMin||!Number.isInteger(s.repMin)||!Number.isInteger(s.repMax)||s.load<0||s.increment<=0){setError('Use whole positive rep ranges, a nonnegative load, and a positive increment.');return}onSave(s)}}>Apply exercise <Check size={17}/></Button></Modal>
}
