import { DayVolume } from './DayVolume';
import { ExerciseSearch } from './ExerciseSearch';
import { PlanExercises } from './PlanExercises';
import { standardEquipment } from './domain/equipment';
import { EquipmentSetup } from './EquipmentSetup';
import { planPrescriptionSignature } from './domain/recovery';
import { planExerciseSchema } from './domain/validation';
import { useState } from 'react';
import { Check, Plus, SlidersHorizontal } from 'lucide-react';
import type { AppData, PlanExercise, Rir, TrainingPlan } from './domain/types';
import { calculateVolume, validatePlan, allocateSets, makeRir } from './domain/engine';
import { MUSCLES } from './data/seed';
import { availableExercises, catalogForPlan } from './data/catalog';
import { Button, Field, Modal, Notice, HelpButton, numberValue } from './components';
import type { Update } from './Train';
export function Plan({data,update}:{data:AppData;update:Update}) {
 const [help,setHelp]=useState(false);const [setLimit,setSetLimit]=useState(6);const [scaleOpen,setScaleOpen]=useState(false);
 const [choosing,setChoosing]=useState(false);const [newSlot,setNewSlot]=useState<PlanExercise>();
 const [draft,setDraft]=useState<TrainingPlan>(()=>structuredClone(data.plan));const [dayIndex,setDayIndex]=useState(0);const [slotId,setSlotId]=useState<string>();const [message,setMessage]=useState('');const [saved,setSaved]=useState(false);const [saving,setSaving]=useState(false);
 const exercises=availableExercises(data.exercises);
 const volumes=calculateVolume(draft,exercises);const issues=validatePlan(draft,exercises,data.settings.strict);const day=draft.days[dayIndex];
 function change(fn:(p:TrainingPlan)=>void){const p=structuredClone(draft);fn(p);if(planPrescriptionSignature(p)!==planPrescriptionSignature(draft))delete p.recovery;setDraft(p);setSaved(false);setMessage('')}
 function allocate(){const result=allocateSets(draft,exercises,data.settings.strict,setLimit);setDraft(result.plan);setSaved(false);setMessage(result.issues.filter(i=>i.severity==='error'||i.code==='target-approximation'||i.code==='targets-missing').map(i=>i.message).join(' ')||'Sets adjusted toward your targets and balanced across training days. Review the plan and save when ready.')}
 async function save(){setSaving(true);try{await update(d=>({...d,exercises:catalogForPlan(d.exercises,draft),plan:{...draft,updatedAt:new Date().toISOString()}}));setSaved(true)}catch(e){setMessage((e as Error).message)}finally{setSaving(false)}}
 return <><header className="page-heading"><div><h1>Your plan</h1><p>{data.settings.strict?'The PANDR-5 framework, fitted to your training.':'Custom mode · your schedule, guided by PANDR-5 progression.'}</p></div><Button primary disabled={saving||issues.some(i=>i.severity==='error')||!!data.activeSession} onClick={()=>void save()}>{saved?'Saved':saving?'Saving…':'Save plan'} <Check size={17}/></Button></header>{data.activeSession&&<Notice>Finish your active session before changing the plan.</Notice>}{message&&<Notice>{message}</Notice>}{saved&&<Notice tone="success">Your plan is saved. It will be used for your next session.</Notice>}
 {data.settings.strict&&data.settings.adaptiveRecovery!==false&&<Notice>Your saved plan is the normal-volume ceiling. Check-ins can temporarily reduce sets within the model’s bounds; Train shows the current prescription. Editing exercises, targets, sets, or RIR starts a new recovery baseline.</Notice>}
 {data.strength?.active&&<Notice>Your unfinished assessment will follow your saved exercise selections. Completed test results and progress for unchanged exercises are kept.</Notice>}
 <section className="panel target-panel"><div className="section-head"><div><h2>Weekly muscle targets</h2><p>The input is your desired weekly effective sets. “Planned” is what your current exercises provide.</p></div><div className="actions"><Button onClick={allocate}><SlidersHorizontal size={17}/> Adjust exercise sets to targets</Button><HelpButton label="How weekly targets and exercise sets work" onClick={()=>setHelp(true)}/></div></div><Field label="Automatic set limit per exercise" hint="Applies when adjusting sets. Lower this to limit each exercise’s automatic allocation; manual prescriptions stay editable."><input type="number" min="1" max="30" step="1" value={setLimit} onChange={e=>setSetLimit(numberValue(e.target.value))}/></Field><div className="target-grid">{MUSCLES.map(m=>{const v=volumes.find(v=>v.muscle===m.id);const target=draft.targets[m.id];return <div className="target-control" key={m.id}><label><input type="checkbox" checked={target!==undefined} onChange={e=>change(p=>{if(e.target.checked)p.targets[m.id]=data.settings.strict?Math.min(20,Math.max(10,v?.total||10)):Math.min(300,Math.max(0,v?.total??10));else delete p.targets[m.id]})}/><strong>{m.name}</strong></label><div><span className={target!==undefined&&((v?.total||0)<10||(v?.total||0)>20)&&data.settings.strict?'warning-text':''}>{v?.total||0} <small>planned</small></span>{target!==undefined&&<input aria-label={`${m.name} target`} type="number" min={data.settings.strict?10:0} max={data.settings.strict?20:300} step="0.25" value={target} onChange={e=>change(p=>{p.targets[m.id]=numberValue(e.target.value)})}/>}</div><div className="bar"><i style={{width:`${Math.min(100,(v?.total||0)/(target||20)*100)}%`}}/></div></div>})}</div><p className="muted">Select the muscles you want to target. In constrained mode, every selected target and its planned effective volume must fall within 10–20 sets, spread over at least two days. Smaller supporting muscles remain visible. Exact targets depend on the exercises you choose.</p></section>
 <div className="week-strip">{draft.days.map((d,i)=><button key={d.id} className={dayIndex===i?'selected':''} onClick={()=>setDayIndex(i)}><span>Day {i+1}</span><strong>{d.name}</strong><i/></button>)}</div>
 <section className="panel"><div className="section-head"><div><h2>{day.name}</h2><p>{day.kind==='training'?`${day.exercises.length} exercises`:'Recovery day'}</p></div>{day.kind==='training'&&<div className="actions"><Button disabled={!!data.activeSession||!day.exercises.length} onClick={()=>setScaleOpen(true)}>Scale day volume</Button><Button disabled={!!data.activeSession} onClick={()=>setChoosing(true)}><Plus size={17}/> Add exercise</Button></div>}</div>
 {!data.settings.strict&&<div className="form-grid"><Field label="Day name"><input value={day.name} onChange={e=>change(p=>{p.days[dayIndex].name=e.target.value})}/></Field><Field label="Day type"><select value={day.kind} onChange={e=>{if(e.target.value==='rest'&&day.exercises.length){setMessage('Remove the exercises from this day before changing it to recovery.');return}change(p=>{p.days[dayIndex].kind=e.target.value as 'rest'|'training'})}}><option value="training">Training</option><option value="rest">Recovery</option></select></Field></div>}
 {!!day.exercises.length&&<PlanExercises key={day.id} slots={day.exercises} exercises={exercises} disabled={!!data.activeSession} onEdit={setSlotId} onRemove={id=>change(p=>{p.days[dayIndex].exercises=p.days[dayIndex].exercises.filter(s=>s.id!==id)})} onReorder={ids=>change(p=>{const slots=p.days[dayIndex].exercises;p.days[dayIndex].exercises=ids.map(id=>slots.find(s=>s.id===id)!)})}/>}
 {day.kind==='rest'&&<p className="muted">A scheduled recovery day. Your weekly check-in chooses active or passive recovery.</p>}</section>
 {issues.length>0&&<section className="panel validation-panel"><h3>Plan checks</h3>{issues.map((i,n)=><p className={i.severity==='error'?'warning-text':'muted'} key={n}>{i.message}</p>)}</section>}
 {help&&<Modal title="How weekly targets work" onClose={()=>setHelp(false)}><p>Your target is the weekly effective-set volume you want for a muscle. Typing a number changes that goal; it does not change your exercises.</p><p>“Planned” adds up the sets in your current plan, including overlap. Four bench-press sets, for example, can contribute four chest sets and fractional sets to supporting muscles.</p><p>“Adjust exercise sets to targets” changes whole working-set counts across your existing exercises to get closer to the selected goals. It balances each selected muscle across the days that train it and respects your automatic set limit. Exercises that contribute to no selected muscle keep their existing sets. One exercise can affect several muscles, so an exact match is not always possible; any remaining mismatch is shown as planned / target. Retained exercises keep at least one set; remove an exercise if you want none of its work.</p><p>For a proportional change to whole days, use Scale day volume beside the day’s exercises. Select the days, choose a reference muscle or percentage, and review the weekly totals.</p><p>Review the resulting sets below, then choose Save plan. Your targets and logged history are kept.</p></Modal>}
 {scaleOpen&&<DayVolume plan={draft} exercises={exercises} dayId={day.id} strict={data.settings.strict} onClose={()=>setScaleOpen(false)} onApply={(plan,message)=>{setDraft(plan);setSaved(false);setMessage(message)}}/>}
 {choosing&&<Modal title="Choose an exercise" onClose={()=>setChoosing(false)}><p>Search the library and select the exercise you want to add.</p><ExerciseSearch exercises={exercises} autoFocus onChoose={e=>{setNewSlot({id:crypto.randomUUID(),exerciseId:e.id,sets:3,repMin:8,repMax:12,rir:makeRir(3),load:0,...standardEquipment(e,data.settings.unit),loadMode:'external'});setChoosing(false)}}/></Modal>}
 {newSlot&&<EditSlot key={newSlot.id} adding slot={newSlot} data={data} onClose={()=>setNewSlot(undefined)} onSave={slot=>{change(p=>{p.days[dayIndex].exercises.push(slot)});setNewSlot(undefined)}}/>}
 {slotId&&<EditSlot slot={day.exercises.find(s=>s.id===slotId)!} data={data} onClose={()=>setSlotId(undefined)} onSave={slot=>{change(p=>{const a=p.days[dayIndex].exercises;a[a.findIndex(s=>s.id===slot.id)]=slot});setSlotId(undefined)}}/>}
 </>
}
function EditSlot({slot,data,onSave,onClose,adding=false}:{slot:PlanExercise;data:AppData;onSave:(slot:PlanExercise)=>void;onClose:()=>void;adding?:boolean}) {
 const exercises=availableExercises(data.exercises);
 const [s,setS]=useState(structuredClone(slot));const [error,setError]=useState('');const e=exercises.find(e=>e.id===s.exerciseId)!;
 return <Modal title={adding?'Add exercise prescription':'Edit exercise prescription'} onClose={onClose}><ExerciseSearch exercises={exercises} selected={e} onChoose={exercise=>{if(exercise.id!==s.exerciseId)setS({...s,exerciseId:exercise.id,load:0,rir:makeRir(s.sets),loadMode:'external',...standardEquipment(exercise,data.settings.unit),bodyweight:undefined})}}/><div className="form-grid"><Field label="Working sets"><input type="number" min="1" max="30" value={s.sets} onChange={e=>{const n=Math.min(30,Math.max(1,Math.round(numberValue(e.target.value,1))));setS({...s,sets:n,rir:makeRir(n,s.rir.at(-1)==='<0')})}}/></Field><Field label="Working load"><input type="number" min="0" step="0.25" disabled={data.settings.strict||s.loadMode==='bodyweight'} value={s.load} onChange={e=>setS({...s,load:numberValue(e.target.value)})}/></Field><Field label="Minimum reps"><input type="number" min="1" value={s.repMin} onChange={e=>setS({...s,repMin:numberValue(e.target.value)})}/></Field><Field label="Maximum reps"><input type="number" min="1" value={s.repMax} onChange={e=>setS({...s,repMax:numberValue(e.target.value)})}/></Field><Field label="Smallest load increment" hint={`Total load change in ${data.settings.unit}; barbell increments include both sides.`}><input type="number" min="0.01" step="any" value={s.increment} onChange={e=>setS({...s,increment:numberValue(e.target.value)})}/></Field><Field label="Load type"><select value={s.loadMode} onChange={e=>setS({...s,loadMode:e.target.value as PlanExercise['loadMode'],load:e.target.value==='bodyweight'?0:s.load})}><option value="external">External weight</option><option value="assistance">Assistance weight</option><option value="bodyweight">Bodyweight only</option></select></Field></div><EquipmentSetup key={s.exerciseId} slot={s} unit={data.settings.unit} onChange={setS}/><h3>RIR staircase</h3><p className="muted">Repetitions in reserve: the clean reps you could still perform. &lt;0 is a beyond-failure finisher.</p><div className="rir-editor">{s.rir.map((r,i)=><Field label={`Set ${i+1}`} key={i}><select value={r} onChange={event=>{const value=event.target.value;setS({...s,rir:s.rir.map((v,j)=>i===j?(value==='0-1'||value==='<0'?value:Number(value)) as Rir:v)})}}>{[3,2,1,'0-1',0,...(e.beyondFailureAllowed&&i===s.sets-1&&i>0?['<0']:[])].map(v=><option key={v} value={v}>{v}</option>)}</select></Field>)}</div>{error&&<Notice tone="error">{error}</Notice>}<Button primary onClick={()=>{if(s.repMin<1||s.repMax<s.repMin||!Number.isInteger(s.repMin)||!Number.isInteger(s.repMax)||s.load<0||s.increment<=0){setError('Use whole positive rep ranges, a nonnegative load, and a positive increment.');return}const test=planExerciseSchema.safeParse(s);if(!test.success){setError(test.error.issues[0].message);return}onSave(s)}}>Apply exercise <Check size={17}/></Button></Modal>
}
