import { useState } from 'react';
import { Download, Upload, Check, Cloud, HardDrive, RefreshCw, ShieldCheck } from 'lucide-react';
import type { AppData, Settings as SettingsType } from './domain/types';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Update } from './Train';
import { validatePlan } from './domain/engine';
import { exportBackup, exportCsv, parseBackup } from './services/backup';
import { requestPersistence } from './services/storage';
import { Button, Field, Modal, Notice, download, readFile, numberValue } from './components';
export function Settings({data,update,client,profile,email,sync,goPlan}:{data:AppData;update:Update;client:SupabaseClient|null;profile:string;email:string;sync:()=>Promise<void>;goPlan:()=>void}) {
 const [draft,setDraft]=useState<SettingsType>(data.settings);const [message,setMessage]=useState('');const [error,setError]=useState('');const [restore,setRestore]=useState<AppData>();const [restorePreview,setRestorePreview]=useState(false);const [saving,setSaving]=useState(false);
 async function save(){setError('');if(data.activeSession){setError('Finish your active session before changing settings.');return}if(draft.increasePercent<2||draft.increasePercent>5||draft.decreasePercent<2||draft.decreasePercent>3||draft.restSeconds<0||!Number.isInteger(draft.restSeconds)||!draft.startDate){setError('Use a 2–5% increase, 2–3% decrease, a start date, and a whole rest duration of at least 0 seconds.');return}const issues=validatePlan(data.plan,data.exercises,draft.strict).filter(i=>i.severity==='error');if(issues.length){setError(`Your plan must be adjusted before enabling these settings. ${issues[0].message}`);return}setSaving(true);try{await update(d=>{if(d.settings.unit!==draft.unit){const factor=draft.unit==='lb'?2.20462262185:1/2.20462262185;d.plan.days.forEach(day=>day.exercises.forEach(e=>{e.load=Math.round(e.load*factor*10000)/10000;e.increment=Math.round(e.increment*factor*10000)/10000}));d.plan.updatedAt=new Date().toISOString()}d.settings=draft;return d});setMessage('Settings saved. Historical sessions keep their original units.')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function stageRestore(file:File){try{const backup=parseBackup(await readFile(file));setRestore(backup);setRestorePreview(true);setError('')}catch(e){setError((e as Error).message)}}
 return <><header className="page-heading"><div><h1>Make it yours</h1><p>Your training preferences, account, and data.</p></div></header>{message&&<Notice tone="success">{message}</Notice>}{error&&<Notice tone="error">{error}</Notice>}
 <div className="settings-grid"><section className="panel"><h2>Training preferences</h2><Field label="Your name"><input placeholder="What should we call you?" value={draft.name} maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><label className="switch-row"><div><h3>Constrained PANDR-5 mode</h3><p>Five training days, non-competing split, 10–20 effective sets for your selected muscles, and the RIR staircase.</p></div><input role="switch" aria-label="Constrained PANDR-5 mode" type="checkbox" checked={draft.strict} onChange={e=>setDraft({...draft,strict:e.target.checked})}/></label><p className="muted">Turn this off to choose any 1–7 training days and weekly volume. Double progression and recovery guidance remain available. Changes take effect when you save.</p><div className="form-grid"><Field label="Weight unit"><select value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value as 'kg'|'lb'})}><option value="kg">Kilograms (kg)</option><option value="lb">Pounds (lb)</option></select></Field><Field label="Week 1 begins"><input type="date" value={draft.startDate} onChange={e=>setDraft({...draft,startDate:e.target.value})}/></Field><Field label="Load increase (%)"><input type="number" min="2" max="5" step="0.5" value={draft.increasePercent} onChange={e=>setDraft({...draft,increasePercent:numberValue(e.target.value)})}/></Field><Field label="Load reduction (%)"><input type="number" min="2" max="3" step="0.5" value={draft.decreasePercent} onChange={e=>setDraft({...draft,decreasePercent:numberValue(e.target.value)})}/></Field><Field label="Rest timer (seconds)" hint="A personal preference, not a new PANDR-5 rule."><input type="number" min="0" max="3600" step="15" value={draft.restSeconds} onChange={e=>setDraft({...draft,restSeconds:numberValue(e.target.value)})}/></Field></div><div className="actions"><Button primary disabled={saving||!!data.activeSession} onClick={()=>void save()}>Save preferences <Check size={17}/></Button><Button onClick={goPlan}>Edit your plan</Button></div></section>
 <div><Account client={client} profile={profile} email={email} sync={sync}/><section className="panel"><h2><HardDrive size={21}/> Your data</h2><p>Training is saved on this device as you log. Export a backup regularly, especially before clearing browser data or changing devices.</p><div className="data-actions"><Button onClick={()=>download('pandr-5-all-time.csv',exportCsv(data),'text/csv;charset=utf-8')}><Download size={17}/> Full all-time CSV</Button><Button onClick={()=>download(`pandr-5-backup-${new Date().toISOString().slice(0,10)}.json`,exportBackup(data),'application/json')}><Download size={17}/> Download complete backup</Button><label className="button"><Upload size={17}/> Restore a backup<input aria-label="Restore a backup" hidden type="file" accept=".json,application/json" disabled={!!data.activeSession} onChange={e=>{const file=e.target.files?.[0];if(file)void stageRestore(file);e.target.value=''}}/></label><Button onClick={async()=>setMessage(await requestPersistence()?'This browser granted persistent storage. Backups are still recommended.':'This browser manages storage automatically. Keep a backup of your training.')}><ShieldCheck size={17}/> Protect local storage</Button></div><small>Your data is private to this device or signed-in account. It is not encrypted at rest by this app; use your device’s screen lock on shared computers.</small></section><section className="panel"><h2>Install PANDR-5</h2><p><strong>Desktop:</strong> download a desktop build, or use “Install app” in Chrome or Edge. On supported Safari versions, use Add to Dock.</p><p><strong>iPhone / iPad:</strong> open the hosted app in Safari, then Share → Add to Home Screen.</p><p><strong>Android:</strong> use Install app or Add to Home screen in Chrome.</p><small>After the first online load, the installed web app works offline. Native desktop downloads bundle the entire app.</small></section></div></div>
 {restorePreview&&restore&&<Modal title="Restore this backup?" onClose={()=>setRestorePreview(false)}><p>{restore.sessions.length} saved sessions, {restore.checkIns.length} check-ins, and {restore.exercises.length} exercises. This replaces the current profile’s local copy; cloud sync may report a conflict if the account already has newer changes.</p><Notice>A backup of your current data will be downloaded before restoring. Keep it to undo this change.</Notice><Button primary onClick={async()=>{try{download('pandr-5-before-restore.json',exportBackup(data),'application/json');await update(()=>restore);setRestorePreview(false);setDraft(restore.settings);setMessage('Backup restored on this device.')}catch(e){setError((e as Error).message)}}}>Back up current data and restore</Button></Modal>}
 </>
}
function Account({client,profile,email,sync}:{client:SupabaseClient|null;profile:string;email:string;sync:()=>Promise<void>}) {
 const [address,setAddress]=useState('');const [password,setPassword]=useState('');const [mode,setMode]=useState<'signin'|'signup'>('signin');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [newPassword,setNewPassword]=useState('');
 async function authenticate(){if(!client)return;setBusy(true);setError('');try{const result=mode==='signup'?await client.auth.signUp({email:address,password}):await client.auth.signInWithPassword({email:address,password});if(result.error)throw result.error;if(mode==='signup'&&!result.data.session)setMessage('Check your email to confirm your account, then sign in here.');setPassword('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><h2><Cloud size={21}/> Your account</h2>{!client?<><p>This build saves locally. Cloud account syncing has not been configured for this release.</p><Notice>Local saving, complete backups, and CSV exports work now. Account access requires the project’s free cloud service to be connected.</Notice></>:profile!=='local'?<><p>Signed in as <strong>{email}</strong></p><p>Changes sync automatically after editing pauses, and after you finish a workout. Offline changes stay on this device until you reconnect.</p><div className="actions"><Button primary onClick={()=>void sync()}><RefreshCw size={17}/> Sync now</Button><Button onClick={()=>void client.auth.signOut().then(({error})=>{if(error)setError(error.message)})}>Sign out</Button></div><details className="password-change"><summary>Change password</summary><Field label="New password"><input type="password" autoComplete="new-password" minLength={12} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></Field><Button disabled={newPassword.length<12} onClick={async()=>{const {error}=await client.auth.updateUser({password:newPassword});setError(error?.message||'');if(!error){setNewPassword('');setMessage('Password updated.')}}}>Save new password</Button></details><p className="muted">Your signed-in account and local profile are kept separate. Signing out returns to the local profile.</p></>:<><p>Create an account to keep your training across devices. This device’s local profile stays separate; use a backup to move that training into your account.</p><form onSubmit={e=>{e.preventDefault();void authenticate()}}><Field label="Email"><input type="email" required autoComplete="email" value={address} onChange={e=>setAddress(e.target.value)}/></Field><Field label="Password"><input type="password" required minLength={12} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></Field><Button primary disabled={busy} type="submit">{busy?'Please wait…':mode==='signup'?'Create account':'Sign in'}</Button></form><button className="text-link" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Create an account':'Already have an account? Sign in'}</button><button className="text-link" onClick={async()=>{if(!address){setError('Enter your email address first.');return}const {error}=await client.auth.resetPasswordForEmail(address);setError(error?.message||'');if(!error)setMessage('If this account exists, a password reset email has been requested.')}}>Forgot password?</button></>}{error&&<Notice tone="error">{error}</Notice>}{message&&<Notice tone="success">{message}</Notice>}</section>
}
