import { useEffect, useState } from 'react';
import { Check, ArrowRight, Clock3, X } from 'lucide-react';
import type { AppData, StrengthDraft } from './domain/types';
import type { Update } from './Train';
import { assessmentEstimate, finishAssessment, fractionAt, fromKg, prescribedSlot, recordAssessment, pauseAssessment } from './domain/strength';
import { EquipmentSetup } from './EquipmentSetup';
import { Button, Field, Notice } from './components';

export function StrengthAssessment({data,update}:{data:AppData;update:Update}) {
 const active=data.strength!.active!;
 const [index,setIndex]=useState(()=>Math.max(0,active.items.findIndex(i=>!i.resultId)));
 const [draft,setDraft]=useState<StrengthDraft>(()=>structuredClone(active.items[index]));
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const [restUntil,setRestUntil]=useState(0);const [now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const saved=active.items[index].resultId;const result=data.strength!.assessments.find(a=>a.id===saved);
 const completed=active.items.filter(i=>i.resultId).length;
 const name=data.exercises.find(e=>e.id===draft.exerciseId)?.name??draft.exerciseId;
 async function saveDraft(){
  if(saved)return true;
  try{await update(d=>{if(d.strength?.active?.id!==active.id)throw new Error('Assessment changed. Reopen Train.');d.strength.active.items[index]=structuredClone(draft);return d});setError('');return true}catch(e){setError((e as Error).message);return false}
 }
 async function select(i:number){setBusy(true);if(await saveDraft()){setIndex(i);setDraft(structuredClone(active.items[i]));setError('')}setBusy(false)}
 async function record(){setBusy(true);try{await update(d=>recordAssessment(d,index,draft));setNow(Date.now());setRestUntil(Date.now()+300000);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const remaining=Math.max(0,Math.ceil((restUntil-now)/1000));
 return <><header className="page-heading"><div><h1>Strength assessment</h1><p>{active.initial?'Initial baseline · required in every mode':'Exercise reassessment'} · {completed} of {active.items.length} exercises tested</p></div><div className="actions"><Button disabled={busy} onClick={async()=>{setBusy(true);try{if(await saveDraft())await update(d=>pauseAssessment(d));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><X size={18}/> Save and exit</Button><Button disabled={busy||completed===0} primary onClick={async()=>{setBusy(true);try{if(await saveDraft())await update(d=>finishAssessment(d));else setBusy(false);}catch(e){setError((e as Error).message);setBusy(false)}}}>Finish assessment <Check size={18}/></Button></div></header>
 <div className="session-progress"><i style={{width:`${completed/active.items.length*100}%`}}/></div>
 <Notice><strong>This visit is for assessment.</strong><p>Warm up before each exercise. Use the same equipment, range of motion, tempo and load convention you will use in training. Prefer a load allowing 3–10 clean reps to momentary failure; 2–15 are accepted. Stop for pain or technique breakdown, and do not count forced reps.</p><p>Rest 3–5 minutes after warm-ups or attempts and longer if needed. Use safeties or a competent spotter where needed. A true 1RM is an option for experienced lifters with a safe setup. Stop testing when fatigue changes performance; save your place and resume on another visit. These tests do not count toward training volume.</p></Notice>
 {error&&<Notice tone="error">{error}</Notice>}
 <div className="logging-grid"><aside className="exercise-picker">{active.items.map((item,i)=><button disabled={busy} className={i===index?'selected':''} key={item.exerciseId} onClick={()=>void select(i)}><span>{String(i+1).padStart(2,'0')}</span><strong>{data.exercises.find(e=>e.id===item.exerciseId)?.name??item.exerciseId}</strong><small>{item.resultId?'Tested':item.reason==='stale'?'14+ days':item.reason==='setup'?'Setup changed':'Baseline needed'}</small></button>)}</aside>
 <section className="panel log-panel assessment-panel"><h2>{name}</h2>{result?<><Notice tone="success"><strong>Baseline saved</strong><p>{result.load} {result.unit} · {result.loadMode} · {result.reps} clean rep{result.reps===1?'':'s'} · {result.method==='1rm'?'tested 1RM':'failure set'}</p></Notice><h3>Your starting workout loads</h3>{data.plan.days.flatMap(day=>day.exercises.filter(slot=>slot.exerciseId===result.exerciseId).map(slot=>{try{const prescription=prescribedSlot(data,slot);return <p key={slot.id}><strong>{day.name}: {prescription.loadMode==='bodyweight'?'Unassisted bodyweight':`${prescription.load} ${data.settings.unit} ${prescription.loadMode==='assistance'?'assistance':'external / added'}`}</strong> · {slot.repMin}–{slot.repMax} reps · RIR {slot.rir.join(' → ')}</p>}catch(e){return <Notice key={slot.id} tone="error">{day.name}: {(e as Error).message}</Notice>}}))}<p className="muted">These calculated loads seed the first workout in program order. After that, PANDR-5 anchor progression controls each subsequent load.</p><h3>Estimated fresh-set capacity</h3><p>{result.setup}</p><p>These are estimates at 0 RIR before equipment rounding, not guaranteed repetitions. Training uses a lighter starting load to allow the prescribed RIR. Bodyweight values below are total resistance moved.</p><div className="strength-estimates">{[1,3,5,8,10,12,15,20].map(reps=><div key={reps}><small>{reps} reps</small><strong>{(fromKg(assessmentEstimate(result),result.unit)*fractionAt(reps,result.curve)).toFixed(1)} {result.unit}</strong></div>)}</div><p className="muted">{result.method==='1rm'?'The single was measured; higher-rep capacities use a population curve.':'One measured point anchors a population curve; predictions farther from the test are less certain.'} {result.curve==='general'?'General':result.curve==='bench'?'Bench press':'Leg press'} curve. No velocity measurement is inferred.</p></>:<>
 <div className="form-grid"><Field label="Test method"><select value={draft.method} onChange={e=>setDraft({...draft,method:e.target.value as StrengthDraft['method'],reps:e.target.value==='1rm'?1:0,confirmed:false})}><option value="failure">Known load to momentary failure</option><option value="1rm">True one-repetition maximum</option></select></Field><Field label={`Test load (${draft.unit})`} hint="Record the same total or per-dumbbell convention every time."><input type="number" min="0" step="any" disabled={draft.loadMode==='bodyweight'} value={draft.load||''} onChange={e=>setDraft({...draft,load:Number(e.target.value),confirmed:false})}/></Field><Field label="Resistance type"><select value={draft.loadMode} onChange={e=>setDraft({...draft,loadMode:e.target.value as StrengthDraft['loadMode'],load:e.target.value==='bodyweight'?0:draft.load,confirmed:false})}><option value="external">External / added load</option><option value="bodyweight">Unassisted bodyweight</option><option value="assistance">Measured assistance</option></select></Field><Field label="Clean repetitions"><input type="number" min={draft.method==='1rm'?1:2} max={draft.method==='1rm'?1:15} disabled={draft.method==='1rm'} value={draft.reps||''} onChange={e=>setDraft({...draft,reps:Number(e.target.value),confirmed:false})}/></Field></div>
 <EquipmentSetup key={draft.exerciseId} slot={{...draft.slot,loadMode:draft.loadMode,load:draft.load}} unit={draft.unit} onChange={slot=>setDraft({...draft,slot,confirmed:false})}/>
 <Field label="Exact setup" hint="Machine / station, seat setting, grip, range of motion, tempo, and whether dumbbell load is per hand. Retest after changing the setup."><textarea maxLength={300} value={draft.setup} onChange={e=>setDraft({...draft,setup:e.target.value,confirmed:false})}/></Field>
 <label className="check-row"><span>{draft.method==='1rm'?'I completed one clean maximum rep without pain, help or reduced range of motion.':'The next clean rep was impossible despite trying; this was 0 RIR, without pain, help or reduced range of motion.'}</span><input type="checkbox" checked={draft.confirmed} onChange={e=>setDraft({...draft,confirmed:e.target.checked})}/></label>
 <div className="actions"><Button disabled={busy} onClick={()=>void saveDraft()}>Save assessment progress</Button><Button primary disabled={busy||!draft.confirmed} onClick={()=>void record()}>Save test result <Check size={17}/></Button></div></>}
 <div className="assessment-rest"><Clock3 size={18}/><span>{remaining?`Rest guide: ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`:'Rest until fully recovered before testing.'}</span></div>
 <div className="actions"><Button disabled={busy||index===0} onClick={()=>void select(index-1)}>Previous</Button><Button disabled={busy||index===active.items.length-1} onClick={()=>void select(index+1)}>Next exercise <ArrowRight size={17}/></Button></div>
 <p className="muted">Saved results and saved progress resume from your account. Save and exit whenever you need a break. You can start a workout once every exercise in that workout has a current baseline, without testing the rest of the program first. You can review equipment in Your plan if no available load fits the estimate.</p>
 </section></div></>;
}
