import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronRight, Clock3, Dumbbell, Pause, RotateCcw } from 'lucide-react';
import type { AppData, Session, CheckIn } from './domain/types';
import { createSession, getDayIndex, getWeek, isPivotWeek, recoveryAdvice, recommendProgression, validatePlan } from './domain/engine';
import { useDeviceTime } from './useDeviceTime';
import { activeCycle, checkInDue, completedWeeklyVolume, inActiveCycle, materializeCycles, localDate, performanceEvidence, recoveryTrend } from './domain/training';
import { completeSession, recordCheckIn, trainingPlan } from './domain/coaching';
import { MUSCLES } from './data/seed';
import { Button, Modal, Notice, Field, numberValue, dateString } from './components';
export type Update=(change:(data:AppData)=>AppData)=>Promise<void>;
export function Train({data,update,goPlan}:{data:AppData;update:Update;goPlan:()=>void}) {
 const now=useDeviceTime();const today=localDate(now);const cycle=activeCycle(data);
 const [selected,setSelected]=useState(()=>getDayIndex(cycle.startDate)%data.plan.days.length);const [checking,setChecking]=useState(false);const [detail,setDetail]=useState<string>();const [allMuscles,setAllMuscles]=useState(false);
 useEffect(()=>{setSelected(getDayIndex(cycle.startDate,now)%data.plan.days.length);setChecking(false)},[today,cycle.startDate,data.plan.days.length]);
 const week=getWeek(cycle.startDate,cycle.endedAt??now);const cycleChecks=useMemo(()=>data.checkIns.filter(c=>inActiveCycle(data,c)),[data]);const cycleSessions=useMemo(()=>data.sessions.filter(s=>inActiveCycle(data,s)),[data]);const pivot=isPivotWeek(cycleChecks,week);const prescribed=trainingPlan(data,week);const day=prescribed.days[selected]||prescribed.days[0];const alreadyTrained=data.settings.strict&&cycleSessions.some(s=>s.week===week&&s.dayId===day.id);const volumes=useMemo(()=>completedWeeklyVolume(data,week),[data,week]);const issues=useMemo(()=>validatePlan(prescribed,data.exercises,data.settings.strict).filter(x=>x.severity==='error'),[prescribed,data.exercises,data.settings.strict]);const due=checkInDue(data,now);const inactive=!!cycle.endedAt||today<cycle.startDate;
 const equipmentNeeds=pivot?[]:day.exercises.flatMap(slot=>{const log=cycleSessions.flatMap(s=>s.exercises).filter(e=>e.slotId===slot.id&&e.exerciseId===slot.exerciseId).at(-1);if(!log||log.load!==slot.load||log.unit!==data.settings.unit||log.sets.length!==slot.sets||JSON.stringify(log.bodyweight)!==JSON.stringify(slot.bodyweight))return [];const rec=recommendProgression({...log,increment:slot.increment,availableLoads:slot.availableLoads},data.settings);return rec.status?[{name:log.name,reason:rec.reason}]:[]});
 if(data.activeSession)return <Workout data={data} update={update}/>;
 async function start(){const session=createSession(day,data.exercises,data.settings,week,pivot);await update(d=>{materializeCycles(d);session.cycleId=activeCycle(d).id;return {...d,activeSession:session}})}
 return <><header className="page-heading"><div><h1>Your next session</h1></div><span className="date-label">{now.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</span></header>
 <div className="week-strip" aria-label="Training week">{data.plan.days.map((d,i)=><button key={d.id} className={selected===i?'selected':''} onClick={()=>setSelected(i)}><span>Day {i+1}</span><strong>{d.name}</strong><i className={cycleSessions.some(s=>s.week===week&&s.dayId===d.id)?'done':''}/></button>)}</div>
 {equipmentNeeds.length>0&&<Notice><strong>Progression setup needs attention</strong>{equipmentNeeds.map(e=><p key={e.name}>{e.name}: {e.reason}</p>)}<button className="text-button" onClick={goPlan}>Review equipment in your plan</button></Notice>}
 {inactive&&<Notice>{cycle.endedAt?`${cycle.name} ended on ${cycle.endedAt}. Start a new cycle in Settings when you return.`:`${cycle.name} starts on ${cycle.startDate}.`}</Notice>}
 {pivot&&<Notice><strong>Pivot week.</strong> Working sets are halved for recovery. Load progression is paused. The next check-in determines whether normal training can resume next week.</Notice>}
 {cycleChecks.filter(c=>c.coaching&&c.coaching.action!=='hold'&&c.coaching.effectiveWeek>=week-1).slice(-1).map(c=><Notice key={c.id}><strong>Recovery adjustment</strong><p>{c.coaching!.reason}</p></Notice>)}
 <div className="train-grid"><section className="panel workout-panel"><div className="section-head"><div><h2>{day.name}</h2><p>{day.kind==='training'?`${day.exercises.length} exercises · ${day.exercises.reduce((n,e)=>n+(pivot?Math.max(1,Math.ceil(e.sets/2)):e.sets),0)} working sets`:'Make room for the next good session.'}</p></div>{day.kind==='training'&&<Button primary disabled={issues.length>0||!day.exercises.length||alreadyTrained||inactive} onClick={()=>void start()}>Start session <ArrowRight size={18}/></Button>}</div>
 {issues.length>0&&<Notice tone="error">Your plan needs attention before strict training. {issues[0].message} <button className="text-button" onClick={goPlan}>Review plan</button></Notice>}
 {alreadyTrained&&<Notice tone="success">This session is saved for week {week}. Choose another scheduled day, or return next week. Custom mode allows additional sessions.</Notice>}
 {day.kind==='rest'?<div className="recovery-content"><div className="recovery-icon"><Pause size={36}/></div><h2>Recovery is part of the plan.</h2><p>Feeling recovered? Follow the sheet’s 20–30 minutes of very easy, conversational aerobic work, then 5–10 minutes of mobility.</p><p>Poor sleep, feeling run-down, elevated resting heart rate, or lingering soreness call for passive rest: easy steps, with no planned cardio.</p><p>No failure work, HIIT, or make-up lifting today.</p>{cycleChecks.filter(c=>c.date===today).map(c=><Notice key={c.id}><strong>Today’s check-in guidance</strong><p>{recoveryAdvice(c)}</p></Notice>)}{due&&<Button primary onClick={()=>setChecking(true)}>Record a check-in <ArrowRight size={18}/></Button>}</div>:<>
 <div className="exercise-table"><div className="exercise-table-head"><span>#</span><span>Exercise</span><span>Sets</span><span>Reps</span><span>RIR</span><span/></div>{day.exercises.map((slot,i)=>{const e=data.exercises.find(x=>x.id===slot.exerciseId);return <button className="exercise-row" key={slot.id} onClick={()=>setDetail(slot.id)}><span className="row-index">{String(i+1).padStart(2,'0')}</span><strong>{e?.name||'Unknown exercise'}</strong><span>{pivot?Math.max(1,Math.ceil(slot.sets/2)):slot.sets}</span><span>{slot.repMin}–{slot.repMax}</span><span>{slot.rir[0]} → {slot.rir.at(-1)}</span><ChevronRight size={16}/></button>})}</div>
 <Notice><strong>Let the last set lead.</strong><p>Reach the top of the rep range on your anchor set at its target RIR. We’ll calculate your next load. A beyond-failure finisher uses the preceding set as the anchor.</p></Notice></>}
 </section><aside className="summary-column"><section className="panel"><h2>This week</h2><p>{cycleSessions.filter(s=>s.week===week).length} / {data.plan.days.filter(d=>d.kind==='training').length} sessions logged · {cycle.name} · Week {week}</p><p className="muted volume-caption">Completed / {pivot?'pivot-week prescription':prescribed!==data.plan?'adjusted weekly prescription':'weekly target'} · effective sets</p><div className="volume-mini">{volumes.filter(v=>allMuscles||v.target!==undefined).slice(0,allMuscles?undefined:5).map(v=><div key={v.muscle}><div><span>{MUSCLES.find(m=>m.id===v.muscle)?.name||v.muscle}</span><span>{v.total} <small>{v.target!==undefined?`/ ${v.target}`:'completed · no target'}</small></span></div>{v.target!==undefined&&<div className="bar" role="progressbar" aria-label={`${MUSCLES.find(m=>m.id===v.muscle)?.name||v.muscle} weekly completed sets`} aria-valuemin={0} aria-valuemax={v.target} aria-valuenow={Math.min(v.total,v.target)} aria-valuetext={`${v.total} of ${v.target} effective sets completed`}><i style={{width:`${v.target>0?Math.min(100,v.total/v.target*100):0}%`}}/></div>}</div>)}</div><button className="text-link" onClick={()=>setAllMuscles(!allMuscles)}>{allMuscles?'Show fewer muscle groups':'View all muscle groups'} <ChevronRight size={17}/></button></section>{due&&<section className="panel"><h3>Weekly check-in</h3><p>Scheduled for today · {cycle.name}, week {week}</p><Button primary onClick={()=>setChecking(true)}>Check in <ArrowRight size={17}/></Button></section>}</aside></div>
 <footer>PANDR-5 v1.1.1 · Your data stays yours</footer>
 {checking&&due&&<CheckInModal data={data} update={update} onClose={()=>setChecking(false)}/>}
 {detail&&(()=>{const slot=day.exercises.find(s=>s.id===detail)!;const e=data.exercises.find(x=>x.id===slot.exerciseId)!;return <Modal title={e.name} onClose={()=>setDetail(undefined)}><p>{slot.sets} working sets · {slot.repMin}–{slot.repMax} reps · one load across all sets</p><div className="rir-stair">{slot.rir.map((r,i)=><div key={i}><small>SET {i+1}</small><strong>{r}</strong><span>RIR</span></div>)}</div><h3>Fractional set allocation</h3>{e.contributions.map(c=><div className="data-line" key={c.muscle}><span>{MUSCLES.find(m=>m.id===c.muscle)?.name||c.muscle}</span><strong>{c.coefficient} per set</strong></div>)}<p className="muted">{e.source}. Credits estimate volume; they are not precise measures of muscle stimulus.</p><Button onClick={()=>{setDetail(undefined);goPlan()}}>Edit in your plan</Button></Modal>})()}
 </>
}
function Workout({data,update}:{data:AppData;update:Update}) {
 const [session,setSession]=useState<Session>(()=>structuredClone(data.activeSession!));const [index,setIndex]=useState(0);const [confirm,setConfirm]=useState(false);const [discard,setDiscard]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [end,setEnd]=useState(0);const [now,setNow]=useState(Date.now());const exercise=session.exercises[index];
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return ()=>clearInterval(t)},[]);
 function restartTimer(){const stamp=Date.now();setNow(stamp);setEnd(stamp+data.settings.restSeconds*1000)}
 const remaining=Math.max(0,Math.ceil((end-now)/1000));const complete=session.exercises.flatMap(e=>e.sets).filter(s=>s.completed).length;const total=session.exercises.reduce((n,e)=>n+e.sets.length,0);
 const rec=recommendProgression(exercise,data.settings,session.pivot);
 async function save(next=session){try{await update(d=>({...d,activeSession:next}));setError('')}catch(e){setError((e as Error).message)}}
 function edit(fn:(s:Session)=>void){const next=structuredClone(session);fn(next);setSession(next);return next}
 async function toggleSet(i:number){const row=exercise.sets[i];if(!row.completed&&(!Number.isFinite(row.reps)||row.reps<1||!Number.isInteger(row.reps)||!Number.isFinite(exercise.load)||exercise.load<0)){setError('Enter a valid load and at least one whole repetition before logging this set.');return}const next=edit(s=>{s.exercises[index].sets[i].completed=!row.completed});await save(next);if(!row.completed)restartTimer()}
 async function finish(){setSaving(true);try{await update(d=>completeSession(d,session,new Date().toISOString()))}catch(e){setError((e as Error).message);setSaving(false)}}
 return <><header className="page-heading"><div><h1>{session.dayName}</h1><p>Week {session.week}{session.pivot?' · Pivot week':''} · {complete} of {total} sets logged</p></div><div className="actions session-actions"><Button onClick={()=>setDiscard(true)}>Discard session</Button><Button disabled={!complete||saving} onClick={()=>setConfirm(true)}>Finish session <Check size={18}/></Button></div></header><div className="session-progress"><i style={{width:`${complete/total*100}%`}}/></div>{error&&<Notice tone="error">{error}</Notice>}
 <div className="logging-grid"><aside className="exercise-picker">{session.exercises.map((e,i)=><button key={e.slotId} className={i===index?'selected':''} onClick={()=>{void save();setIndex(i)}}><span>{String(i+1).padStart(2,'0')}</span><strong>{e.name}</strong><small>{e.sets.filter(s=>s.completed).length}/{e.sets.length}</small></button>)}</aside><section className="panel log-panel"><div className="section-head"><div><span className="muted">Exercise {index+1} of {session.exercises.length}</span><h2>{exercise.name}</h2><p>{exercise.repMin}–{exercise.repMax} reps · {exercise.loadMode==='assistance'?'assistance load':exercise.loadMode==='bodyweight'?'bodyweight':'external load'}</p></div><Dumbbell size={28}/></div><div className="load-row"><Field label={`Working load (${exercise.unit})`} hint="The same load for every working set."><input aria-label="Working load" disabled={exercise.loadMode==='bodyweight'} type="number" min="0" step="0.25" value={exercise.load} onChange={e=>edit(s=>{s.exercises[index].load=numberValue(e.target.value)})} onBlur={()=>void save()}/></Field><div className="timer"><Clock3 size={20}/><strong>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong><button className="icon-button" aria-label="Restart rest timer" onClick={restartTimer}><RotateCcw size={17}/></button></div></div>
 <div className="set-table"><div className="set-row labels"><span>Set</span><span>Target RIR</span><span>Reps</span><span>Actual RIR</span><span>Log</span></div>{exercise.sets.map((s,i)=><div className={`set-row ${s.completed?'completed':''}`} key={i}><span>{i+1}{i===rec.anchorIndex&&<small className="anchor">Anchor</small>}</span><strong>{exercise.targetRir[i]}</strong><input aria-label={`Set ${i+1} reps`} type="number" min="0" max="1000" value={s.reps||''} placeholder="—" onChange={e=>edit(next=>{next.exercises[index].sets[i].reps=numberValue(e.target.value)})} onBlur={()=>void save()}/><select aria-label={`Set ${i+1} actual RIR`} value={s.rir} onChange={e=>{const next=edit(next=>{next.exercises[index].sets[i].rir=numberValue(e.target.value)});void save(next)}}>{[-1,0,0.5,1,2,3,4,5,6,7,8,9,10].map(r=><option key={r} value={r}>{r===-1?'<0':r}</option>)}</select><button className={`log-check ${s.completed?'checked':''}`} aria-label={`${s.completed?'Unlog':'Log'} set ${i+1}`} onClick={()=>void toggleSet(i)}><Check size={20}/></button></div>)}</div>
 <Notice><strong>{rec.status==='equipment-needed'?'Equipment needs attention':rec.status==='bodyweight-setup'?'Bodyweight setup needed':rec.action==='increase'?'Ready to progress':rec.action==='decrease'?'Adjust the next load':'Your next-session guidance'}</strong><p>{rec.reason}</p><p>Next load: <b>{(rec.nextLoadMode??exercise.loadMode)==='bodyweight'?'Unassisted bodyweight':`${rec.nextLoad} ${exercise.unit} ${(rec.nextLoadMode??exercise.loadMode)==='assistance'?'assistance':exercise.bodyweight?'added load':''}`}</b> · target {rec.targetReps} reps</p></Notice><Field label="Exercise notes"><textarea placeholder="Technique, equipment, or anything to remember…" value={exercise.notes} onChange={e=>edit(s=>{s.exercises[index].notes=e.target.value})} onBlur={()=>void save()}/></Field><div className="actions"><Button disabled={index===0} onClick={()=>{void save();setIndex(i=>i-1)}}>Previous</Button><Button primary disabled={index===session.exercises.length-1} onClick={()=>{void save();setIndex(i=>i+1)}}>Next exercise <ArrowRight size={17}/></Button></div></section></div>
 {discard&&<Modal title="Discard the current session?" onClose={()=>setDiscard(false)}><p>This removes the in-progress session, including its {complete} logged sets. Your completed history and plan are kept.</p><Button onClick={()=>setDiscard(false)}>Keep training</Button><Button primary onClick={async()=>{await update(d=>{d.activeSession=undefined;return d})}}>Discard this session</Button></Modal>}
 {confirm&&<Modal title="Finish this session?" onClose={()=>setConfirm(false)}><p>{complete} working sets will be saved to your history. Next-session loads follow your completed anchor sets.</p>{complete<total&&<Notice>{total-complete} sets are unlogged. These are kept as incomplete, and exercises without a valid anchor will hold their load.</Notice>}<Field label="Session notes"><textarea value={session.notes} onChange={e=>edit(s=>{s.notes=e.target.value})}/></Field><Button primary disabled={saving} onClick={()=>void finish()}>{saving?'Saving…':complete===total?'Save completed session':`Finish with ${total-complete} unlogged sets`}</Button></Modal>}
 </>
}
export function CheckInModal({data,update,onClose}:{data:AppData;update:Update;onClose:()=>void}) {
 const now=useDeviceTime();const cycle=activeCycle(data);const evidence=useMemo(()=>performanceEvidence(data.sessions.filter(s=>inActiveCycle(data,s)),getWeek(cycle.startDate,now)),[data,localDate(now)]);
 const [check,setCheck]=useState<CheckIn>({id:crypto.randomUUID(),date:dateString(),week:getWeek(cycle.startDate),poorSleep:false,runDown:false,elevatedHr:false,lingeringSoreness:false,performanceDip:false,jointPain:false,notes:''});
 const flags=[['poorSleep','Repeated poor sleep this week compared with your usual sleep'],['runDown','Feeling run-down today'],['elevatedHr','Resting heart rate repeatedly above your usual morning baseline'],['lingeringSoreness','Soreness still limiting normal movement'],['performanceDip','Performance has declined across comparable workouts'],['jointPain','Persistent or recurring joint pain']] as const;
 const [saving,setSaving]=useState(false);const [error,setError]=useState('');return <Modal title="How are you recovering?" onClose={onClose}><p>Compare this week with your usual recovery. Leave optional measurements blank if unknown.</p><div className="form-grid"><Field label="Average sleep per night (hours)"><input type="number" min="0" max="24" step="0.25" value={check.sleepHours??''} onChange={e=>setCheck({...check,sleepHours:e.target.value===''?undefined:Number(e.target.value)})}/></Field>{([['fatigue','Fatigue'],['soreness','Muscle soreness'],['stress','Stress']] as const).map(([key,label])=><Field key={key} label={`${label} this week`}><select value={check[key]??''} onChange={e=>setCheck({...check,[key]:e.target.value===''?undefined:Number(e.target.value)})}><option value="">Not recorded</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {n===1?'very low':n===2?'low':n===3?'moderate':n===4?'high':'very high'}</option>)}</select></Field>)}</div>{flags.map(([key,label])=><label className="check-row" key={key}><span>{label}</span><input type="checkbox" checked={check[key]} onChange={e=>setCheck({...check,[key]:e.target.checked})}/></label>)}<Notice>{recoveryAdvice(check)}</Notice>{evidence.length>0&&<Notice><strong>From your workout log</strong>{evidence.map(line=><p key={line}>{line}</p>)}<p>{evidence.length>=2?'Declines on at least two exercises count as one performance flag.':'One confirmed decline is shown for context; it does not add a flag.'}</p></Notice>}{recoveryTrend(check,data.checkIns.filter(c=>inActiveCycle(data,c))).map(line=><p key={line}>{line}</p>)}<p className="muted">Logged declines require a confirmed drop or a repeated downward trend across five comparable anchors, beyond ordinary one-rep variation. Repeated recovery trouble can also reduce next week’s normal sets within the 10–20 bounds; three recovered, attended normal weeks allow gradual restoration toward your chosen plan.</p><p className="muted">Two of repeated poor sleep, declining performance (reported or logged), and joint pain trigger the PANDR-5 pivot next week: half the sets, rounded up, with load progression paused. This is a conservative model rule. Ratings and sleep hours track your own trend; they do not predict muscle growth or independently change your loads.</p><Field label="Notes"><textarea value={check.notes} onChange={e=>setCheck({...check,notes:e.target.value})}/></Field>{error&&<Notice tone="error">{error}</Notice>}<Button primary disabled={saving||!checkInDue(data,now)} onClick={async()=>{setSaving(true);try{await update(d=>{if(!checkInDue(d))throw new Error('Check-in is available only on your scheduled day, once per training week.');return recordCheckIn(d,{...check,date:dateString(),week:getWeek(activeCycle(d).startDate)})});onClose()}catch(e){setError((e as Error).message);setSaving(false)}}}>Save check-in <Check size={17}/></Button></Modal>
}
