// Generated by scripts/extract-source.py from the supplied live sheet.
// Exercise equipment labels are UI descriptors; every coefficient comes from J/K formulas.
import type { AppData, Exercise, TrainingPlan } from '../domain/types';

export const SOURCE_URL = "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit";

export const MUSCLES = [
  {
    "id": "chest",
    "name": "Chest (pec major)"
  },
  {
    "id": "anterior-delts",
    "name": "Anterior Delts"
  },
  {
    "id": "lateral-delts",
    "name": "Lateral Delts"
  },
  {
    "id": "rear-delts",
    "name": "Rear Delts"
  },
  {
    "id": "triceps",
    "name": "Triceps"
  },
  {
    "id": "biceps",
    "name": "Biceps (Brachii)"
  },
  {
    "id": "brachialis",
    "name": "Brachialis"
  },
  {
    "id": "brachioradialis",
    "name": "Brachioradial."
  },
  {
    "id": "lats",
    "name": "Lats / teres major"
  },
  {
    "id": "mid-low-traps-rhomboids",
    "name": "Mid / Low Traps & Rhomboids"
  },
  {
    "id": "upper-traps",
    "name": "Upper Traps"
  },
  {
    "id": "quads",
    "name": "Quads"
  },
  {
    "id": "hamstrings",
    "name": "Hamstrings"
  },
  {
    "id": "glute-max",
    "name": "Glute max"
  },
  {
    "id": "glute-med-min",
    "name": "Glute med/min"
  },
  {
    "id": "adductors",
    "name": "Adductors"
  },
  {
    "id": "gastrocnemius",
    "name": "Gastroc."
  },
  {
    "id": "soleus",
    "name": "Soleus"
  },
  {
    "id": "erector-spinae",
    "name": "Erector Spinae"
  }
];

export const SOURCE_TOTALS = {
  "chest": {
    "direct": 20.0,
    "fractional": 0.0,
    "total": 20.0
  },
  "anterior-delts": {
    "direct": 0.0,
    "fractional": 7.0,
    "total": 7.0
  },
  "lateral-delts": {
    "direct": 9.0,
    "fractional": 0.0,
    "total": 9.0
  },
  "rear-delts": {
    "direct": 0.0,
    "fractional": 5.0,
    "total": 5.0
  },
  "triceps": {
    "direct": 15.0,
    "fractional": 3.5,
    "total": 18.5
  },
  "biceps": {
    "direct": 7.0,
    "fractional": 8.0,
    "total": 15.0
  },
  "brachialis": {
    "direct": 3.0,
    "fractional": 3.5,
    "total": 6.5
  },
  "brachioradialis": {
    "direct": 0.0,
    "fractional": 3.25,
    "total": 3.25
  },
  "lats": {
    "direct": 20.0,
    "fractional": 0.0,
    "total": 20.0
  },
  "mid-low-traps-rhomboids": {
    "direct": 0.0,
    "fractional": 5.0,
    "total": 5.0
  },
  "upper-traps": {
    "direct": 0.0,
    "fractional": 0.0,
    "total": 0.0
  },
  "quads": {
    "direct": 20.0,
    "fractional": 0.0,
    "total": 20.0
  },
  "hamstrings": {
    "direct": 12.0,
    "fractional": 7.5,
    "total": 19.5
  },
  "glute-max": {
    "direct": 3.0,
    "fractional": 8.75,
    "total": 11.75
  },
  "glute-med-min": {
    "direct": 0.0,
    "fractional": 1.5,
    "total": 1.5
  },
  "adductors": {
    "direct": 0.0,
    "fractional": 4.75,
    "total": 4.75
  },
  "gastrocnemius": {
    "direct": 10.0,
    "fractional": 0.0,
    "total": 10.0
  },
  "soleus": {
    "direct": 0.0,
    "fractional": 5.0,
    "total": 5.0
  },
  "erector-spinae": {
    "direct": 0.0,
    "fractional": 4.0,
    "total": 4.0
  }
};

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    "id": "source-5",
    "name": "Bench Press",
    "equipment": "Barbell",
    "contributions": [
      {
        "muscle": "chest",
        "coefficient": 1.0
      },
      {
        "muscle": "anterior-delts",
        "coefficient": 0.5
      },
      {
        "muscle": "triceps",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C5:F5",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-6",
    "name": "Incline Dumbbell Press",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "chest",
        "coefficient": 1.0
      },
      {
        "muscle": "anterior-delts",
        "coefficient": 0.5
      },
      {
        "muscle": "triceps",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C6:F6",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-7",
    "name": "Machine Chest Flyes",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "chest",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C7:F7",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-8",
    "name": "Close-Grip Chinups (Assisted, BW, or Weighted)",
    "equipment": "Bodyweight",
    "contributions": [
      {
        "muscle": "rear-delts",
        "coefficient": 0.25
      },
      {
        "muscle": "biceps",
        "coefficient": 0.5
      },
      {
        "muscle": "lats",
        "coefficient": 1.0
      },
      {
        "muscle": "mid-low-traps-rhomboids",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C8:F8",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-9",
    "name": "Preacher Curls (Machine)",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "biceps",
        "coefficient": 1.0
      },
      {
        "muscle": "brachialis",
        "coefficient": 0.5
      },
      {
        "muscle": "brachioradialis",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C9:F9",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-10",
    "name": "Hammer Curls",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "biceps",
        "coefficient": 0.5
      },
      {
        "muscle": "brachialis",
        "coefficient": 1.0
      },
      {
        "muscle": "brachioradialis",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C10:F10",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-11",
    "name": "Lateral Raise",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "lateral-delts",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C11:F11",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-13",
    "name": "Single-Arm Bent-Over Dumbbell Row",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "rear-delts",
        "coefficient": 0.5
      },
      {
        "muscle": "biceps",
        "coefficient": 0.5
      },
      {
        "muscle": "lats",
        "coefficient": 1.0
      },
      {
        "muscle": "mid-low-traps-rhomboids",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C13:F13",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-14",
    "name": "Lat Pulldown (Standard Bar)",
    "equipment": "Cable",
    "contributions": [
      {
        "muscle": "rear-delts",
        "coefficient": 0.25
      },
      {
        "muscle": "biceps",
        "coefficient": 0.5
      },
      {
        "muscle": "lats",
        "coefficient": 1.0
      },
      {
        "muscle": "mid-low-traps-rhomboids",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C14:F14",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-15",
    "name": "Lat Pullovers (Cable; any attachment)",
    "equipment": "Cable",
    "contributions": [
      {
        "muscle": "lats",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C15:F15",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-16",
    "name": "Ez-Bar Tricep Overhead Extension",
    "equipment": "Barbell",
    "contributions": [
      {
        "muscle": "triceps",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C16:F16",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-17",
    "name": "Tricep Cable Pushdown (preferred attachment)",
    "equipment": "Cable",
    "contributions": [
      {
        "muscle": "triceps",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C17:F17",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-18",
    "name": "Tricep Cable Overhead Extension (preferred attachment)",
    "equipment": "Cable",
    "contributions": [
      {
        "muscle": "triceps",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C18:F18",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-20",
    "name": "Seated Hamstring Curls",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "hamstrings",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C20:F20",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-21",
    "name": "RDL (Barbell or Dumbell)",
    "equipment": "Barbell",
    "contributions": [
      {
        "muscle": "hamstrings",
        "coefficient": 1.0
      },
      {
        "muscle": "glute-max",
        "coefficient": 0.5
      },
      {
        "muscle": "adductors",
        "coefficient": 0.25
      },
      {
        "muscle": "erector-spinae",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C21:F21",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-22",
    "name": "Leg Press",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "quads",
        "coefficient": 1.0
      },
      {
        "muscle": "hamstrings",
        "coefficient": 0.5
      },
      {
        "muscle": "glute-max",
        "coefficient": 0.5
      },
      {
        "muscle": "adductors",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C22:F22",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-23",
    "name": "Dumbbell Heel-Elevated Squat",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "quads",
        "coefficient": 1.0
      },
      {
        "muscle": "glute-max",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C23:F23",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-24",
    "name": "Leg Extension",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "quads",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C24:F24",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-25",
    "name": "Standing Calf Raise (Machine)",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "gastrocnemius",
        "coefficient": 1.0
      },
      {
        "muscle": "soleus",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C25:F25",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-30",
    "name": "Wide-Grip Seated Cable Rows",
    "equipment": "Cable",
    "contributions": [
      {
        "muscle": "rear-delts",
        "coefficient": 0.5
      },
      {
        "muscle": "biceps",
        "coefficient": 0.5
      },
      {
        "muscle": "lats",
        "coefficient": 1.0
      },
      {
        "muscle": "mid-low-traps-rhomboids",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C30:F30",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-34",
    "name": "Incline/Elevated Pushups",
    "equipment": "Bodyweight",
    "contributions": [
      {
        "muscle": "chest",
        "coefficient": 1.0
      },
      {
        "muscle": "anterior-delts",
        "coefficient": 0.5
      },
      {
        "muscle": "triceps",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C34:F34",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-35",
    "name": "Incline Curls",
    "equipment": "Dumbbell",
    "contributions": [
      {
        "muscle": "biceps",
        "coefficient": 1.0
      },
      {
        "muscle": "brachialis",
        "coefficient": 0.5
      },
      {
        "muscle": "brachioradialis",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C35:F35",
    "beyondFailureAllowed": true
  },
  {
    "id": "source-39",
    "name": "Lying Hamstring Curls",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "hamstrings",
        "coefficient": 1.0
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C39:F39",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-40",
    "name": "45° Hip Extension",
    "equipment": "Other",
    "contributions": [
      {
        "muscle": "hamstrings",
        "coefficient": 0.5
      },
      {
        "muscle": "glute-max",
        "coefficient": 0.5
      },
      {
        "muscle": "adductors",
        "coefficient": 0.25
      },
      {
        "muscle": "erector-spinae",
        "coefficient": 0.5
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C40:F40",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-41",
    "name": "Hack Squat",
    "equipment": "Machine",
    "contributions": [
      {
        "muscle": "quads",
        "coefficient": 1.0
      },
      {
        "muscle": "hamstrings",
        "coefficient": 0.5
      },
      {
        "muscle": "glute-max",
        "coefficient": 0.5
      },
      {
        "muscle": "adductors",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C41:F41",
    "beyondFailureAllowed": false
  },
  {
    "id": "source-43",
    "name": "Lunges",
    "equipment": "Other",
    "contributions": [
      {
        "muscle": "quads",
        "coefficient": 1.0
      },
      {
        "muscle": "hamstrings",
        "coefficient": 0.5
      },
      {
        "muscle": "glute-max",
        "coefficient": 1.0
      },
      {
        "muscle": "glute-med-min",
        "coefficient": 0.5
      },
      {
        "muscle": "adductors",
        "coefficient": 0.25
      }
    ],
    "source": "https://docs.google.com/spreadsheets/d/1o7sQkxG_r72CH2Dv7CJDyqhSzbeBVhoKN6BVWNjcGjk/edit#gid=0&range=C43:F43",
    "beyondFailureAllowed": false
  }
];

export const DEFAULT_PLAN: TrainingPlan = {
  "id": "pandr5-source-v1.1.1",
  "name": "PANDR-5 · Source template",
  "days": [
    {
      "id": "push",
      "name": "Push + NCP",
      "kind": "training",
      "exercises": [
        {
          "id": "slot-5",
          "exerciseId": "source-5",
          "sets": 4,
          "repMin": 5,
          "repMax": 8,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-6",
          "exerciseId": "source-6",
          "sets": 3,
          "repMin": 8,
          "repMax": 11,
          "rir": [
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-7",
          "exerciseId": "source-7",
          "sets": 3,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            1,
            0,
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-8",
          "exerciseId": "source-8",
          "sets": 2,
          "repMin": 5,
          "repMax": 7,
          "rir": [
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "bodyweight"
        },
        {
          "id": "slot-9",
          "exerciseId": "source-9",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-10",
          "exerciseId": "source-10",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-11",
          "exerciseId": "source-11",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        }
      ]
    },
    {
      "id": "pull",
      "name": "Pull + NCP",
      "kind": "training",
      "exercises": [
        {
          "id": "slot-13",
          "exerciseId": "source-13",
          "sets": 3,
          "repMin": 6,
          "repMax": 9,
          "rir": [
            3,
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-14",
          "exerciseId": "source-14",
          "sets": 4,
          "repMin": 8,
          "repMax": 11,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-15",
          "exerciseId": "source-15",
          "sets": 3,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-16",
          "exerciseId": "source-16",
          "sets": 3,
          "repMin": 6,
          "repMax": 9,
          "rir": [
            3,
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-17",
          "exerciseId": "source-17",
          "sets": 3,
          "repMin": 10,
          "repMax": 12,
          "rir": [
            3,
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-18",
          "exerciseId": "source-18",
          "sets": 3,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        }
      ]
    },
    {
      "id": "legs",
      "name": "Legs",
      "kind": "training",
      "exercises": [
        {
          "id": "slot-20",
          "exerciseId": "source-20",
          "sets": 4,
          "repMin": 8,
          "repMax": 10,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-21",
          "exerciseId": "source-21",
          "sets": 4,
          "repMin": 5,
          "repMax": 8,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-22",
          "exerciseId": "source-22",
          "sets": 4,
          "repMin": 6,
          "repMax": 9,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-23",
          "exerciseId": "source-23",
          "sets": 3,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-24",
          "exerciseId": "source-24",
          "sets": 3,
          "repMin": 10,
          "repMax": 12,
          "rir": [
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-25",
          "exerciseId": "source-25",
          "sets": 5,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            3,
            2,
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-26",
          "exerciseId": "source-11",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        }
      ]
    },
    {
      "id": "rest-1",
      "name": "Active Rest",
      "kind": "rest",
      "exercises": []
    },
    {
      "id": "upper",
      "name": "Upper",
      "kind": "training",
      "exercises": [
        {
          "id": "slot-30",
          "exerciseId": "source-30",
          "sets": 4,
          "repMin": 8,
          "repMax": 10,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-31",
          "exerciseId": "source-15",
          "sets": 4,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            3,
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-32",
          "exerciseId": "source-6",
          "sets": 4,
          "repMin": 6,
          "repMax": 9,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-33",
          "exerciseId": "source-7",
          "sets": 3,
          "repMin": 10,
          "repMax": 12,
          "rir": [
            3,
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-34",
          "exerciseId": "source-34",
          "sets": 3,
          "repMin": 10,
          "repMax": 20,
          "rir": [
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "bodyweight"
        },
        {
          "id": "slot-35",
          "exerciseId": "source-35",
          "sets": 4,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            2,
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-36",
          "exerciseId": "source-17",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-37",
          "exerciseId": "source-18",
          "sets": 3,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        }
      ]
    },
    {
      "id": "lower",
      "name": "Lower",
      "kind": "training",
      "exercises": [
        {
          "id": "slot-39",
          "exerciseId": "source-39",
          "sets": 4,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-40",
          "exerciseId": "source-40",
          "sets": 4,
          "repMin": 10,
          "repMax": 15,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-41",
          "exerciseId": "source-41",
          "sets": 4,
          "repMin": 5,
          "repMax": 8,
          "rir": [
            3,
            2,
            1,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-42",
          "exerciseId": "source-24",
          "sets": 3,
          "repMin": 10,
          "repMax": 12,
          "rir": [
            2,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-43",
          "exerciseId": "source-43",
          "sets": 3,
          "repMin": 7,
          "repMax": 10,
          "rir": [
            3,
            2,
            "0-1"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-44",
          "exerciseId": "source-25",
          "sets": 5,
          "repMin": 12,
          "repMax": 15,
          "rir": [
            3,
            2,
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        },
        {
          "id": "slot-45",
          "exerciseId": "source-11",
          "sets": 3,
          "repMin": 8,
          "repMax": 12,
          "rir": [
            1,
            "0-1",
            "<0"
          ],
          "load": 0,
          "increment": 0.5,
          "loadMode": "external"
        }
      ]
    },
    {
      "id": "rest-2",
      "name": "Active Rest",
      "kind": "rest",
      "exercises": []
    }
  ],
  "targets": {
    "chest": 20,
    "lats": 20,
    "biceps": 15.0,
    "triceps": 18.5,
    "quads": 20,
    "hamstrings": 19.5,
    "glute-max": 11.75,
    "gastrocnemius": 10,
    "lateral-delts": 10
  },
  "updatedAt": "2026-09-15T00:00:00.000Z"
};

export function createInitialData(): AppData {
  const now = new Date();
  const startDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
  return {
    schemaVersion: 1,
    id: crypto.randomUUID(),
    updatedAt: now.toISOString(),
    settings: { name: '', strict: true, unit: 'kg', startDate, increasePercent: 2.5, decreasePercent: 2.5, restSeconds: 120 },
    plan: structuredClone(DEFAULT_PLAN),
    exercises: structuredClone(DEFAULT_EXERCISES),
    sessions: [],
    checkIns: [],
  };
}
